exercism/v3

- README.md
Closes https://github.com/exercism/v3/issues/7
Closes https://github.com/exercism/v3/pull/9
This was just a copy/paste error and shouldn't be there.
> Fix accidental copy and paste

- languages/julia/README.md
This is mostly to test if codeowners work but also an actual addition to the types because it's a common issue among beginners (see survey in the readme)
> julia: add array indexing & link to doc

- .github/workflows/julia-ci.yml
Preparation for adding more concept exercises. Runs the basic track CI to test the Julia concept exercises.
It only triggers builds if files ending in `.jl` or in the `languages/julia/` directory are changed, so it should not affect anyone else's work.
> julia: Add CI

- docs/rationale-for-v3.md
I believe this is supposed to be `formerly`, not `formally`.
> Typo in rationale for v3

- docs/maintainers/determining-concepts.md
I've reworded things slightly. My main aim was to give clear rules about all concepts/concept exercises, and have a distinctive paragraph about the multiple trivial ideas.
As a side note, we are capitalizing `Concept` and `Concept Exercise`, as I am treating both as Proper Nouns in the context of Exercism. (e.g. It helps when you have sentences like "I get the concept of Concepts")
> Reword information on concept exercises for clarity

- languages/csharp/reference/code_style.md
dot net lang documentation was consolidated to a central `dotnet` repository
See: https://github.com/dotnet/corefx
This broken link is currently marking the following PRs as having problems:
#131, #130 , #129, #128, #127, #120, #99 & #63
> Correct broken link

- .github/markdown-link-check-config.json
- .github/workflows/valid-links.yml
Absolute links are slow and problematic, so I'm blocking them for now. As we improve the link checker we can add this back, either as part of CI or a periodic check, long before v3 is launched.
> Do not check absolute links

- .github/workflows/rebase.workflow
- .github/workflows/rebase.yml
This enables us to add comments for `/rebase`, rather than continuously merging master onto branches.
> Add rebase workflow

- languages/haskell/README.md
- languages/haskell/config.json
This stub contains all things necessary but the list of exercises.
The example C# config.json did not contain the fields `ignore_pattern` and `solution_pattern` present in Haskell's config.json, but the [migration guide][1] also did not speak of deprecating any properties.
For this reason, this PR preserves those properties and adds new ones.
[1]: https://github.com/exercism/v3/blob/master/docs/maintainers/migrating-your-config-json-files.md
> [Haskell] v3 config.json stub

- languages/erlang/README.md
- languages/erlang/config.json
The current settings for the online editor ar by far set in stone.
I've choosen them for now as those are the defaults in the emacs `erlang-mode` which seems to be pretty the standard editor for most Erlang developers.
Though on the other hand side, about every other Erlang project you take a look at, uses slightly different conventions.
Though an indent of either 2 or 4 seems to be quite common, but I've also seen projects that have an indent of 4 but do half indent for some language constructs.
> [erlang] initial migration of config

- .github/workflows/rebase.yml
There was an issue where the rebase GH action did not work. This was due to only the latest commit being fetched. The fix was documented [here](https://github.com/cirrus-actions/rebase/issues/32#event-2960363002).
> [CI] Fix rebase action not working

- .github/workflows/valid-links.yml
This PR attempt to greatly improve the speed with which the markdown link checker runs. It does this by using `git diff-tree` to list the files that have been added or modified in the latest commit. This is probably not what we want, as we'd probably want all the files that have been added or modified in the complete PR. If someone has suggestions on how best to do this, let me know! (there is also a GH action to do this: https://github.com/marketplace/actions/get-changed-files).
This should help alleviate part of #102.
> [CI] Only check markdown for added or modified files

- .github/labeler.yml
Changes to the ISSUE_TEMPLATE are labelled as CI changes, see e.g. https://github.com/exercism/v3/pull/291
> [CI] Apply correct label to ISSUE_TEMPLATE changes

- languages/go/reference/exercise-concepts/two-fer.md
> [Go] Concepts needed to solve the v2 two fer exercise

- languages/rust/reference/exercise-concepts/parallel-letter-frequency.md
Initial list with concept level abstraction of common elements used for solving `parallel-letter-frequency`.
Something I'm not entirely certain about is the separation of "Tuples" and "Destructuring". But since destructuring can also be applied to structs (and soon for slices [will also be in stable](https://github.com/rust-lang/rust/pull/67712)) I placed it as it's own concept.
> [Rust] Extract Concepts from v2 exercise parallel-letter-frequency

- languages/_sidebar.md
The `/languages/_sidebar.md` file had a typo in the slug of the language name.
Fixes #366.
> [Common Lisp] correct typo of language name in sidebar.

- docs/maintainers/migrating-your-config-json-files.md
This PR tries to make the migration guide a bit more clear. It now specifies that the `"foregone"` property should be removed and that in principle, the existing `config.json` file can be used _as is_.
> [Docs] Add note about removing "foregone" property

- languages/csharp/reference/exercise-concepts/protein-translation.md
Solves #264 
There turned out to be more concepts than what I was originally imagining for such a straight-forward exercise. Let me know if any of the concepts are too fine grained.
> [C#] Add concepts for protein-translation exercise

- .github/workflows/julia-ci.yml
PRs that change the documentation (like #436) don't need to run the exercise test suite.
> [Julia] Only run CI when exercises are touched

- languages/scala/reference/exercise-concepts/hamming.md
Initial attempt at extracting hamming concepts. Refs #295
> [Scala] Extract concepts of v2 hamming exercise

- languages/csharp/exercises/concept/numbers/NumbersTest.cs
Noticed this tiny typo when working on the Go implementation for this exercise so thought I'd throw in a fix :)
> Fix small typo in C# Numbers Concept Exercise

- languages/javascript/docs/implementing-a-concept-exercise.md
- languages/typescript/README.md
- languages/typescript/docs/implementing-a-concept-exercise.md
- languages/typescript/exercises/concept/README.md
- languages/typescript/exercises/concept/numbers.md
- languages/typescript/exercises/concept/promises.md
- languages/typescript/exercises/concept/strings.md
- added `implementing-a-concept-exercise.md ` to the typescript track
- fixed minor issues I noticed on the javascript equivalent document.
> [TypeScript] Add implementing a concept docs

- languages/rust/maintainers.md
I noticed other tracks encode maintainer identity differently (First
Name, Last Name, Handle on Github, etc). I like that idea but cannot
justify breaking the visual consistency on our page so kept it to my GH
handle.
> [Rust] add myself as a maintainer

- languages/go/exercises/concept/numbers/.docs/after.md
- languages/go/exercises/concept/numbers/.docs/hints.md
- languages/go/exercises/concept/numbers/.docs/instructions.md
- languages/go/exercises/concept/numbers/.docs/introduction.md
- languages/go/exercises/concept/numbers/.meta/example.go
- languages/go/exercises/concept/numbers/go.mod
- languages/go/exercises/concept/numbers/numbers.go
- languages/go/exercises/concept/numbers/numbers_test.go
I've taken the approach outlined in the C# example but I'm not entirely confident that this is the correct approach for an intro exercise as it requires type conversion. This may be OK but I'd like to others opinions on it.
As Go has quite a few different numeric types, I've limited it to just `int` and `float64` and given links in to the introduction if students want to dig in more.
This satisfies #371
> [Go] Add numbers concept exercise

- languages/go/exercises/concept/basic-strings/.meta/design.md
- languages/go/exercises/concept/numbers/.meta/design.md
Add the missing `design.md` documents to `strings` and `numbers` exercises for Go.
> [Go] add design documents for strings and numbers

- docs/maintainers/README.md
- index.html
- languages/julia/reference/progression.md
Codeblocks with the language set to mermaid will be rendered as mermaid graphs.
For example, 
```mermaid
graph TD
A((A)) --> robots
subgraph Multiple Dispatch
robots --> encounters
robots -.-> abstract-types
abstract-types[abstract types] -.-> modules
modules -.-> encounters
encounters -.-> extension[extending/glueing together modules]
end
extension --> B
B --> performance
performance --> Z((Z))
```
is rendered as the following graph: https://user-images.githubusercontent.com/20866761/73282965-abe4a180-41f2-11ea-8968-54faaaf7c91e.png
This can be quite useful when visualising and planning the progression. Unfortunately, it requires adding a dependency/external script to the website.
> [Docs] Render mermaid graph code blocks

- .github/workflows/valid-links.yml
See https://github.com/exercism/v3/pull/222#issuecomment-580209054. 
Also my address part of the problem in #102.
I also double quoted "$file" variable to avoid globing surprises per [shellcheck.net](https://www.shellcheck.net/).
For the quick and easy way to test this,  [see my testing branch.](https://github.com/exercism/v3/compare/master...efx:polish-link-checker-testing?expand=1). I was only able to reproduce when running `action.sh` from #222.
> exclude .git/ from valid-link workflows

- reference/types/floating_point_number.md
- reference/types/string.md
Once we've defined Concepts and start writing exercises we want to share as much of the load as is reasonably possible. 
There are two types of sharing here:
1. Sharing the various things that need to be taught about a Concept (part of this is helping maintainers understand how concepts might be wildly different in different languages)
2. Sharing the actual exercises that teach them, and the thinking behind those exercises.
I'm entirely open to suggestions on how best to structure these, but would like people to consider the goals above when working out what might be best.
My first attempt splits up the file into:
- The CS concept
- The teaching points
- Exercises and their implementations (that other tracks can learn from and/or fork)
> Flesh out the concept files to include exercise info

- languages/kotlin/docs/implementing-a-concept-exercise.md
According to recent clarifications, there should be a `config.json` file under the `.meta` folder. If is intended to host information of contributors to the exercise. 
Sample: [C# - strings/.meta](https://github.com/exercism/v3/tree/master/languages/csharp/exercises/concept/strings/.meta)
> Add config.json to structure of exercise file tree

- languages/rust/reference/README.md
This is introduced early in the Book and I've observed it come up while teaching Rust to professional developers. 
@lewisclement also rightly pointed it out reviewing luhn's concepts: https://github.com/exercism/v3/pull/679#pullrequestreview-359102357
> [Rust] add variable shadowing

- languages/rust/reference/README.md
I linked the entire match section to the relevant chapter in the book
because it describes them  interchangeably.
> [Rust] Link to concepts in the Book

- languages/csharp/reference/exercise-concepts/resistor-color.md
make sure to add the correct definition to the correct concept.
> [C#] rectify a wrong definition

- docs/concept-exercises.md
- docs/maintainers/generic-how-to-implement-a-concept-exercise.md
- languages/clojure/docs/implementing-a-concept-exercise.md
- languages/common-lisp/docs/implementing-a-concept-exercise.md
- languages/cpp/docs/implementing-a-concept-exercise.md
- languages/csharp/docs/implementing-a-concept-exercise.md
- languages/fsharp/docs/implementing-a-concept-exercise.md
- languages/go/docs/implementing-a-concept-exercise.md
- languages/haskell/docs/implementing-a-concept-exercise.md
- languages/javascript/docs/implementing-a-concept-exercise.md
- languages/julia/docs/implementing-a-concept-exercise.md
- languages/kotlin/docs/implementing-a-concept-exercise.md
- languages/purescript/docs/implementing-a-concept-exercise.md
- languages/typescript/docs/implementing-a-concept-exercise.md
We've recently re-introduced the `config.json` file. It currently only lists the contributors to an exercise, but that might change in the future.
> [Docs] Describe config.json file usage

- languages/clojure/_sidebar.md
- languages/clojure/exercises/README.md
- languages/clojure/exercises/concept/README.md
- languages/clojure/exercises/practice/README.md
- languages/clojure/reference/README.md
- languages/clojure/reference/progression.md
Includes mermaidjs Concepts graph based on Clojure Atlas, and updated sidebar with proper reference docs. Note: this PR replaces #271.
> [Clojure] Add reference/progression.md

- languages/common-lisp/reference/README.md
Hello fellow lispers!
Here are some first-draft concepts compiled from v2 PRs and the language standard.
This is [the sort of thing we are going for](https://github.com/exercism/v3/blob/master/languages/csharp/reference/README.md). There is a ways to go still, but I'm looking for feedback from the others before writing up the formal list of concepts (the `numbers-basic` sort of slugs).
Let me know what you think and please add the things that I've missed!
TODO:
Thanks!
> [Common Lisp] Add Initial Concepts for Discussion

- languages/rust/reference/README.md
> [Rust] fix concept reference list formatting

- languages/python/maintainers.md
Removes @paparomeo from maintainers.md, per https://github.com/exercism/python/pull/2185.
> [Python] Remove paparomeo from maintainers.md

- .github/workflows/concept-ci.yml
It will fail because the track detection would compare master to master
> [CI] Don't run concept checks on pushes to master

- languages/fsharp/reference/examples/new-concept-exercise-strings.md
This PR normalizes the new concept exercise issue example a bit, and also updates some C# track links to F# documents instead.
> [F#] Update new concept exercise issue example

- languages/common-lisp/README.md
- languages/common-lisp/reference/README.md
- languages/common-lisp/reference/implementing-a-concept-exercise.md
Just some tiny updates to the documentation fixing some typos and adding links to our implemented exercise.
> [Common Lisp] Update Some Documentation with the `sexpr` Exercise

- .github/workflows/valid-links.yml
This makes the link checker work for PR's that have manually merged commits.
> [CI] Merge instead of rebasing in link checker

- languages/c/README.md
We have had the kick-off session and the maintainers markdown file has several senior and new maintainers listed :)
> tick kick-off & maintainers prep status

- .github/workflows/concept-ci.yml
- languages/julia/reference/concepts.csv
Since [release 20200308](https://github.com/actions/virtual-environments/releases/tag/ubuntu18%2F20200308.0) of the GH Actions environments, the latest version of Julia is preinstalled on the GH Actions VMs.
> [CI] Use system Julia instead of installing it

- .github/workflows/concept-ci.yml
To prevent sysimage cache from expiring after not being accessed for 7 days, run the workflow every 6 days. Due to the long time needed to build the sysimage, this should overall save time.
> [CI] Run concept CI on a schedule to prevent stale cache

- languages/rust/reference/README.md
- languages/rust/reference/concepts.csv
- languages/rust/reference/out-of-scope.md
This PR reflects _many_ discussions, on Slack and in issues, e.g. #695 
It is intended to parallel PR #681.
The test runner referred to is here: https://github.com/exercism/rust-test-runner/blob/master/Dockerfile
And the student UI can, as of this writing, be witnessed here: https://research.exercism.io/
Inclusion of this document is intended to resolve many questions that have been raised about what is and is not teachable, what should and should not be taught, within the Rust track. It documents the complications such as the web UI and Exercism's intended focus within the context of Rust, and names some examples of beyond-scope topics as a result (e.g. the Cargo CLI, FFI with C, etc.)
In addition, this PR nominates some out-of-scope ("CS-y" or software-design-related) concepts for …
> [Rust] Add out-of-scope.md, remove some concepts

- docs/concept-exercises.md
- docs/maintainers/generic-how-to-implement-a-concept-exercise.md
- languages/csharp/reference/examples/new-concept-exercise-arrays.md
- languages/elixir/reference/implementing-a-concept-exercise.md
- languages/elm/reference/implementing-a-concept-exercise.md
- languages/fsharp/reference/examples/new-concept-exercise-strings.md
- languages/javascript/reference/implementing-a-concept-exercise.md
- languages/kotlin/reference/implementing-a-concept-exercise.md
- languages/typescript/reference/implementing-a-concept-exercise.md
The after.md document should include newly introduced syntax.
> [Docs] Add syntax mention to after.md document description

- languages/go/exercises/concept/README.md
- languages/go/reference/README.md
- reference/types/number.md
- reference/types/slice.md
- reference/types/string.md
part of #837 
I've added links for the following exercises:
numbers
basic-strings
+
extra links to general OOP concepts
> [Go] add links to existing exercises/documentation: 837

- languages/cpp/exercises/concept/strings/CMakeLists.txt
- languages/cpp/reference/implementing-a-concept-exercise.md
When running CMake configure step for an exercise the library is downloaded automatically, this prevents the need to store the header in every single exercise.
> [C++] Catch testing lib is now downloaded automatically

- reference/types/string.md
Add `strings` exercise of `javascript` to the `reference/strings` document.
> [JavaScript] Add JavaScript implementation of strings to ref

- docs/maintainers/generic-how-to-implement-a-concept-exercise.md
- languages/clojure/reference/implementing-a-concept-exercise.md
- languages/common-lisp/reference/implementing-a-concept-exercise.md
- languages/cpp/reference/implementing-a-concept-exercise.md
- languages/csharp/reference/implementing-a-concept-exercise.md
- languages/elixir/reference/implementing-a-concept-exercise.md
- languages/elm/reference/implementing-a-concept-exercise.md
- languages/fsharp/reference/implementing-a-concept-exercise.md
- languages/go/reference/implementing-a-concept-exercise.md
- languages/haskell/reference/implementing-a-concept-exercise.md
- languages/java/reference/implementing-a-concept-exercise.md
- languages/javascript/reference/implementing-a-concept-exercise.md
- languages/julia/reference/implementing-a-concept-exercise.md
- languages/kotlin/reference/implementing-a-concept-exercise.md
- languages/purescript/reference/implementing-a-concept-exercise.md
- languages/python/reference/implementing-a-concept-exercise.md
- languages/ruby/reference/implementing-a-concept-exercise.md
- languages/rust/reference/implementing-a-concept-exercise.md
- languages/typescript/reference/implementing-a-concept-exercise.md
I've found that people start working on these PR's to implement exercises without reading up on any of the v3 documentation, and thus don't know _why_ some things are done in a particular way. We should encourage people to read up on the documentation.
> [Docs] Add reference to required reading in implementing guide

- docs/concept-exercises.md
Fixed:
* Broken link
* F# version string
> [Docs] Fix `.meta/config.json` examples

- languages/clojure/exercises/concept/lists/.meta/config.json
comma added to json to separate contributors
> I was using something in the config as a reference one when i saw the typo
> [Clojure] Update config.json

- Dockerfile
- docs/maintainers/website.md
Happy to document this where appropriate. In the meantime, here are a few notes for using on a Unixy system where you have Docker installed.
1. From the root of this repository, build the docker image:
```sh
docker build . -t exercism-node:v1
```
2. Run the container that has everything configured:
```
docker run -it --rm --name exercism-website -p 3005:3005 -v "$PWD":/usr/src/app exercism-node:v1
```
> [docs] introduce a Dockerfile for the website

- languages/python/exercises/concept/strings/.meta/config.json
Updates as per changes to the file schema, converted `contributors` -> `authors` and added the `forked_from` field. ATM we have no existing PRs for other exercises, only Issues, so we'll just have to ensure future PRs follow the new standard.
Closes #1192.
> [Python] Update .meta/config.json

- docs/concept-exercises.md
We're suffering from people not reading these docs. I'm putting a video to help. This PR addresses the following to help:
- Clearly specifies the purpose of each file to give quick overviews
- More bullet points and less prose to provide extra information
- Incorporates some of @mikedamay's points in https://github.com/exercism/v3/issues/1087
We can improve the other sections later - but if everyone agrees this is an improvement, let's get it down on master.
> [Docs] Flesh out the rules for concept-exercies.md slightly more

- languages/haskell/exercises/shared/.docs/README.md
- languages/haskell/exercises/shared/.docs/cli.md
- languages/haskell/exercises/shared/.docs/debug.md
This is regarding #544  
Let me know if I can improve something. 
I had a doubt regarding the debugging part after I copied the README file from C# and it mentions debugging in browser. I don't know how the browser experience will look for Haskell so I wrote how I would debug the Haskell exercises in current version of Exercism.
> [Haskell] Shared docs CLI and Debug

- languages/elixir/exercises/concept/README.md
Fixes a typo in the `exercises/concept/README.md`
> [Elixir] Typo in README.md

- languages/csharp/exercises/concept/basics/.meta/Example.cs
- languages/csharp/exercises/concept/basics/BasicsTests.cs
- languages/csharp/exercises/concept/datetimes/.meta/Example.cs
- languages/csharp/exercises/concept/datetimes/DateTimesTests.cs
- languages/csharp/exercises/concept/enums/.meta/Example.cs
- languages/csharp/exercises/concept/enums/EnumsTests.cs
- languages/csharp/exercises/concept/flag-enums/.meta/Example.cs
- languages/csharp/exercises/concept/flag-enums/FlagEnumsTests.cs
- languages/csharp/exercises/concept/floating-point-numbers/.meta/Example.cs
- languages/csharp/exercises/concept/floating-point-numbers/FloatingPointNumbersTests.cs
- languages/csharp/exercises/concept/numbers/.meta/Example.cs
- languages/csharp/exercises/concept/numbers/NumbersTests.cs
- languages/csharp/exercises/concept/properties/.meta/Example.cs
- languages/csharp/exercises/concept/strings/.meta/Example.cs
- languages/csharp/exercises/concept/strings/StringsTests.cs
Many of the examples and all the tests were using expression-bodied methods. However, the example files will be used as canonical examples on how we expect the student to solve the exercise, and the student is not guaranteed to know about expression-bodied members at this point (there _will_ be an expression-bodied members exercise, but not at this point in the curriculum).
Similarly, the test files will be downloaded to a student's machine if using the CLI, so we write them in a format that students should at least be able to understand.
> [C#] Normalize code

- .github/bin/validate_json.py
Found a typo in the python script, needs the extra `**/` to correctly expand to all directories.
Sorry.
> [CI] JSON validation needs `**/**/` in glob path

- languages/csharp/exercises/concept/basics/.docs/after.md
- languages/csharp/exercises/concept/basics/.docs/introduction.md
This allows us to use named parameters in exercise instructions, which can help make them concise _and_ still readable. For an illustration, compare the following three options:
```csharp
// Named arguments
SavingsAccount.YearsBeforeDesiredBalance(balance: 200.75m, targetBalance: 214.88m);
// Non-named arguments
SavingsAccount.YearsBeforeDesiredBalance(200.75m, 214.88m);
// Variables
var balance = 200.75m;
var targetBalance = 214.88m;
SavingsAccount.YearsBeforeDesiredBalance(balance, targetBalance);
```
> [C#] Add named parameter reference to basics exercise

- .github/workflows/verify-markdown-formatting.yml
The filtering used `.md` to filter, but it should have been `\\.md`
> [CI] Fix escaping in markdown formatting match

- languages/_sidebar.md
- languages/emacs-lisp/_sidebar.md
- languages/emacs-lisp/reference/README.md
In merging #908 and #967, Markdown formatting CI runs failed due to the PRs existing before these formatting checks were run. This PR runs `npx prettier@2.0.4 --write "**/*.md"` to fix these files.
> [Emacs Lisp] Fix Markdown formatting from old merge

- .github/workflows/rebase.yml
This workaround appears to be no longer needed: https://github.com/exercism/v3/actions/runs/84521868
> [CI] Remove always_job in rebase workflow

- docs/maintainers/repository-structure.md
Motivation: Sometimes it turns out that an exercise idea doesn't work, or that a concept should not be taught. This status allows one to tell apart such issues/PRs from issues/PRs that have been closed due to being fixed or abandoned.
> [Docs] Add status/wontfix label

- reference/concepts/assignment.md
The common lisp track does not have an exercise about assignment as ofyet.
I think it was simply mistakenly added in #1158.
> Remove ref. to common lisp track.

- languages/rust/reference/concepts.csv
Test driven development is out of scope for the Rust track.
See
https://github.com/exercism/v3/blob/master/languages/rust/reference/out-of-scope.md
for other examples.
> [Rust] remove testing from concepts.csv

- languages/common-lisp/reference/README.md
- languages/common-lisp/reference/concepts.csv
The enumerate concept exercise will focus on the basics of `loop` and
will discuss in its after other parts of `loop` as well as `do`.  It
does not seem that an extensive breakdown of `loop` as a concept is
needed anymore.
> Simplify concept lists - removing separate "loop"

- languages/c/reference/implementing-a-concept-exercise.md
On the C track not all of the track specific files are C code files. One is a make file and there is a subdirectory. Further, referring to header files as C source files, while not incorrect, may be confusing.
> [C] correct description of track specific files

- languages/csharp/exercises/concept/arrays/.meta/Example.cs
- languages/csharp/exercises/concept/arrays/Arrays.cs
- languages/csharp/exercises/concept/datetimes/.meta/Example.cs
- languages/csharp/exercises/concept/datetimes/DateTimes.cs
- languages/csharp/exercises/concept/enums/.docs/after.md
- languages/csharp/exercises/concept/enums/.docs/introduction.md
- languages/csharp/exercises/concept/enums/.meta/Example.cs
- languages/csharp/exercises/concept/enums/Enums.cs
- languages/csharp/exercises/concept/flag-enums/.docs/after.md
- languages/csharp/exercises/concept/flag-enums/.docs/introduction.md
- languages/csharp/exercises/concept/flag-enums/.meta/Example.cs
- languages/csharp/exercises/concept/flag-enums/FlagEnums.cs
- languages/csharp/exercises/concept/floating-point-numbers/.meta/Example.cs
- languages/csharp/exercises/concept/floating-point-numbers/FloatingPointNumbers.cs
- languages/csharp/exercises/concept/nullability/.meta/Example.cs
- languages/csharp/exercises/concept/nullability/Nullability.cs
- languages/csharp/exercises/concept/numbers/.meta/Example.cs
- languages/csharp/exercises/concept/numbers/Numbers.cs
- languages/csharp/exercises/concept/properties/.docs/after.md
- languages/csharp/exercises/concept/properties/.meta/Example.cs
- languages/csharp/exercises/concept/properties/Properties.cs
- languages/csharp/exercises/concept/strings/.meta/Example.cs
- languages/csharp/exercises/concept/strings/Strings.cs
I've only just realised that all the stubs used `public` before the class name. Strictly speaking this is not necessary, and as I've [removed the `public class` introduction in the basics exercise](https://github.com/exercism/v3/pull/1368), we can't expect students to know about this feature anymore. I've removed this introduction from the basics exercise to keep things as simple as possible.
The plan is to introduce public classes and visibility of classes in the accessibility exercise (that I might rename to namespaces). If an exercise depends on the "accessibility" (or possibly "namespaces") concept, we can then use `public` classes in those stubs.
> [C#] Simplify classes

- languages/javascript/exercises/concept/strings/.docs/after.md
- languages/javascript/exercises/concept/strings/.docs/instructions.md
- languages/javascript/exercises/concept/strings/.docs/introduction.md
This PR and #1353 resolve #1298.
I add `after.md` to the string concept exercise and rewrite `introduction.md`.
I don't think it's not helpful for beginners or can be confusing that knowing JavaScript strings are UTF-16 encoded strings and JavaScript strings have primitives and objects, so I don't mention them at `after.md`.
I also rewrite `introduction.md` to make it easier for students to get started the exercise.
> [JavaScript] Improve Concept Exercise: strings

- languages/ruby/exercises/concept/basics/lasagna.rb
It seems that we accidentally leaked out constants into the stub. This removes them.
> [Ruby/lasagna] Remove constants from stub

- reference/stories/arrays.magician-card-stack.md
- reference/stories/booleans.pac-man.md
- reference/stories/booleans.rpg-quest-logic.md
- reference/stories/deep-dig.basketball-team-website.md
- reference/stories/lambda-function.secret-device.md
- reference/stories/lists.language-list.md
- reference/stories/maps.high-score-board.md
- reference/stories/numbers.freelancer-rates.md
- reference/stories/promises.klingon-translation-service.md
- reference/stories/strings.poetry-club-door-policy.md
- reference/types/list.md
I've tried to make the format for the stories consistent. What I've done is:
- Have an explicit `## Story` section if there wasn't one. This section describes the story.
- Add a `## Implementations` section if there wasn't one. This section lists the implementations of this story.
- Add a `(reference implementation)` suffix to the reference implementation, to make the format used in the reference documents.
- Any links to exercise now link to the `instructions.md` document, which is probably the best way to quickly get an idea of how the story is implemented.
And some other, minor changes. The format is up for debate, so let me know what you think!
> [Reference] Use consistent format for stories

- .gitignore
- .vscode/settings.json
VScode allows workspace specific settings throgh the use of the .vscode/settings.json file.  Inclusion of this file in the repo disallows personal workspace settings.
Patching to revert that inclusion.
> [General] revert inclusion of .vscode settings file

- languages/csharp/exercises/concept/arrays/ArraysTests.cs
- languages/csharp/exercises/concept/basics/BasicsTests.cs
- languages/csharp/exercises/concept/booleans/BooleansTests.cs
- languages/csharp/exercises/concept/classes/ClassesTests.cs
- languages/csharp/exercises/concept/constructors/ConstructorsTests.cs
- languages/csharp/exercises/concept/datetimes/DateTimesTests.cs
- languages/csharp/exercises/concept/enums/EnumsTests.cs
- languages/csharp/exercises/concept/flag-enums/FlagEnumsTests.cs
- languages/csharp/exercises/concept/floating-point-numbers/FloatingPointNumbersTests.cs
- languages/csharp/exercises/concept/nullability/NullabilityTests.cs
- languages/csharp/exercises/concept/numbers/NumbersTests.cs
- languages/csharp/exercises/concept/properties/PropertiesTests.cs
- languages/csharp/exercises/concept/strings/StringsTests.cs
- languages/csharp/reference/implementing-a-concept-exercise.md
We used inconsistent test method naming. I've updated the convention to use to `snake_case` with the first character uppercased.
> [C#] Update test naming

- languages/csharp/exercises/concept/properties/.meta/Example.cs
- languages/csharp/exercises/concept/properties/PropertiesTests.cs
This PR tries to simplify the syntax features used. It removes:
- Expression-bodied members
- Don't use tuples
> [C#] [Properties] Use basic syntax

- languages/elixir/reference/implementing-a-concept-exercise.md
When I was preparing myself to start working on my first concept exercise, I noticed a few discrepancies between `implementing-a-concept-exercise.md` and already implemented exercises. I am assuming that the exercises are correct, so I am fixing the reference.
> [Elixir] Fix example solution path in Implementing a Concept Exercise reference

- languages/elixir/exercises/concept/basics/mix.exs
- languages/elixir/exercises/concept/conditionals/mix.exs
- languages/elixir/exercises/concept/lists/mix.exs
- languages/elixir/exercises/concept/maps/mix.exs
- languages/elixir/exercises/concept/strings/mix.exs
- languages/elixir/exercises/concept/tuples/mix.exs
A decision was made to comment Elixir version requirements out of `mix.exs` for backwards compatibility since some package manager versions are out of date, preventing less experienced users being able to run it.
> [Elixir] Do not require specific Elixir versions

- languages/elixir/exercises/concept/anonymous-functions/.docs/after.md
- languages/elixir/exercises/concept/anonymous-functions/.docs/introduction.md
- languages/elixir/exercises/concept/tuples/.docs/after.md
Referring to the [style guide](https://github.com/exercism/v3/blob/master/docs/maintainers/style-guide.md), headings now fixed for each of the student-facing exercise docs.
All headings standardized to level 2 headings (e.g. `## heading`).  No other substantive changes made.
---
I've included @SleeplessByte for review as he is often involved in website-copy.
> [Elixir] Patch exercise .docs *.md headings

- languages/elixir/exercises/concept/basics/.docs/after.md
- languages/elixir/exercises/concept/basics/.docs/introduction.md
Some improvements to the basics exercise' introduction and after document.
I have added some content re: `@doc` and `@moduledoc` as comment types (rather than as heredoc strings attached to module attributes).
> [Elixir] Improve concept exercise: basics

- languages/elixir/exercises/concept/anonymous-functions/.docs/after.md
- languages/elixir/exercises/concept/anonymous-functions/.docs/instructions.md
- languages/elixir/exercises/concept/anonymous-functions/.meta/design.md
- languages/elixir/exercises/concept/basics/.docs/hints.md
- languages/elixir/exercises/concept/basics/.meta/design.md
- languages/elixir/exercises/concept/booleans/.docs/hints.md
- languages/elixir/exercises/concept/conditionals/.docs/after.md
- languages/elixir/exercises/concept/conditionals/.docs/introduction.md
- languages/elixir/exercises/concept/conditionals/.meta/design.md
- languages/elixir/exercises/concept/maps/.docs/after.md
- languages/elixir/exercises/concept/maps/.docs/introduction.md
- languages/elixir/exercises/concept/maps/.meta/design.md
- languages/elixir/exercises/concept/maps/test/high_score_test.exs
- languages/elixir/exercises/concept/multiple-clause-functions/.docs/after.md
- languages/elixir/exercises/concept/multiple-clause-functions/.docs/introduction.md
- languages/elixir/exercises/concept/multiple-clause-functions/.meta/design.md
- languages/elixir/exercises/concept/tuples/.docs/after.md
- languages/elixir/exercises/concept/tuples/.docs/hints.md
- languages/elixir/exercises/concept/tuples/.docs/introduction.md
- languages/elixir/exercises/concept/tuples/.meta/design.md
- languages/elixir/exercises/concept/tuples/test/kitchen_calculator_test.exs
- languages/elixir/reference/README.md
- languages/elixir/reference/exercise-concepts/pangram.md
I am dealing with my lack of inspiration for writing docs for new exercises by procrastinating by doing this, not very important cleanup 🤷‍♀️
> [Elixir] Fix typos and uppercase the language name in various docs

- .github/workflows/concept-ci.yml
@SaschaMann I've had several PR submitters experience failures of the Concept CI workflow that they couldn't actually solve (it was unrelated to their PR). As a temporary fix, I think this change would just always return 0 and thus have the workflow always success, correct? Once there is a proper fix for the issue, we can remove this workaround.
> [CI] Have concept CI not fail

- bin/format.sh
On some systems, bash does not exist in `/bin`. I change 2 things for
better compatibility across Unixy environments:
- use `/usr/bin/env` to resolve where the shell is
- use `sh` since we are not doing anything bash specific and `sh` is
decidedly minimal
> improve compatibility of bin/format.sh

- languages/elixir/exercises/concept/recursion/.docs/hints.md
- languages/elixir/exercises/concept/strings/.docs/hints.md
"Pattern matching" as a noun needs to be spelled without a dash. See https://github.com/exercism/v3/pull/1506#discussion_r431312236
> [Elixir] Spell the noun "pattern matching" without a dash

- .github/workflows/format-code.yml
Currently, the `/format` command does not trigger CI itself because it uses the default actions token which does not have permission to trigger other workflows. This means that the commit created by `/format` will get the PR stuck in a state where it can't be merged because required checks, like `valid-links`, haven't been run (see #1434). By using an SSH deploy key, we can get around that restriction. The deploy key, unlike personal access tokens, only has access to this repo.
Proof of concept/test PR: https://github.com/SaschaMann/v3/pull/5
This requires some manual setup before it works:
- Create a new SSH key pair using `ssh-keygen -t ed25519`, ideally in a temporary directory. Do not set a password for the key.
- Add the public key `id_ed25519.pub` as a deploy key to this repo in the …
> [CI] Make /format trigger CI

- languages/fsharp/exercises/concept/discriminated-unions/.docs/after.md
- languages/fsharp/exercises/concept/discriminated-unions/.docs/introduction.md
- languages/fsharp/exercises/concept/floating-point-numbers/.docs/after.md
- languages/fsharp/exercises/concept/floating-point-numbers/.docs/hints.md
- languages/fsharp/exercises/concept/floating-point-numbers/.docs/introduction.md
- languages/fsharp/exercises/concept/floating-point-numbers/.meta/Example.fs
- languages/fsharp/exercises/concept/floating-point-numbers/FloatingPointNumbers.fs
- languages/fsharp/exercises/concept/numbers/.docs/after.md
- languages/fsharp/exercises/concept/numbers/.docs/hints.md
- languages/fsharp/exercises/concept/numbers/.docs/instructions.md
- languages/fsharp/exercises/concept/numbers/.docs/introduction.md
- languages/fsharp/exercises/concept/numbers/.meta/Example.fs
- languages/fsharp/exercises/concept/numbers/.meta/design.md
- languages/fsharp/exercises/concept/numbers/Numbers.fs
I found that we used `double` in a lot of places. This is a remnant of it being a C# port, as in F#, the `float` type is preferred (`double` _is_ an alias for that type though). This PR fixes that.
> [F#] Use float instead of double

- languages/nim/README.md
- languages/nim/config.json
Migrated from the old [`config.json`](https://github.com/exercism/nim/blob/master/config.json).
Note that we should probably improve the `blurb` sometime. The `blurb` here is just the old one.
> [Nim] Add initial `config.json`

- .github/workflows/format-code.yml
The deploy key doesn't have access to push to forks, even if the "allow edits by maintainers" checkbox is enabled. This commit implements a fallback so that /format will still run on PRs from forks, but not trigger CI. If it's not a fork, the deploy key can push to the branch, and CI will be triggered automatically.
* If the PR branch is on a fork, use HTTPS. This will *not* trigger CI to run on the commit automatically.
* If the PR branch is on the exercism/v3 repo, use SSH.
---
It's hard to test if something works on a fork with just one user account (and GH doesn't permit more than that for human accounts), so this is untested. Ping me on Slack if you want to give it a try on a different testing repo.
> [CI] /format fallback to HTTPS on forks

- languages/csharp/exercises/concept/datetimes/.docs/instructions.md
- languages/fsharp/exercises/concept/datetimes/.docs/instructions.md
- reference/stories/datetimes.appointment-scheduler.md
As I was reading the story, I noticed it says to handle 4 different formats, but one of them was repeated. In the unit tests in both interpretations, there are only 3 different formats tested.
> [C#][F#] Remove duplicate datetime format from the appointment scheduler story

- languages/csharp/config.json
- languages/csharp/exercises/concept/user-defined-exceptions/.docs/after.md
- languages/csharp/exercises/concept/user-defined-exceptions/.docs/hints.md
- languages/csharp/exercises/concept/user-defined-exceptions/.docs/instructions.md
- languages/csharp/exercises/concept/user-defined-exceptions/.docs/introduction.md
- languages/csharp/exercises/concept/user-defined-exceptions/.meta/Example.cs
- languages/csharp/exercises/concept/user-defined-exceptions/.meta/config.json
- languages/csharp/exercises/concept/user-defined-exceptions/.meta/design.md
- languages/csharp/exercises/concept/user-defined-exceptions/UserDefinedExceptions.csproj
- languages/csharp/exercises/concept/user-defined-exceptions/UserDefinedExceptionsTests.cs
- languages/csharp/exercises/concept/user-defined-exceptions/UserDefinedExceptons.cs
1.  Please review _UserDefinedExceptions.cs_ as part of your initial review of this draft.
2. @ErikSchierboom I know you are averse to including language features in the test file that are not pre-requisites for the exercise.  We need lambdas in the test file but I don't really want to increase the dependency count.  I did half the Haskell track without really understanding how the test framework worked so I'm not so committed to this principle as you.  However, I am happy to fall into line if necessary.
3. I was in two minds about whether to include less boilerplate in the code provided for `CalculationException` but decided against it on the grounds that it could multiply the number of representations required.  I can't really judge
> [C#] Add exercise User-defined Exceptions

- languages/csharp/config.json
The slug was out of sync with the directory name (which was the correct name)
> [C#] Fix invalid exercise name

- languages/rust/_sidebar.md
- languages/rust/exercises/README.md
- languages/rust/exercises/practice/README.md
You need to add `_sidebar.md` files to relevant directories for them to appear in the [documentation website](https://exercism.github.io/v3/#/). Thanks to @SleeplessByte for pointing that out to me.
> [docs] connect Rust documentation to website

- languages/clojure/config.json
- languages/clojure/exercises/concept/README.md
Added concept lists as per [[Clojure] Missing exercise entries in config.json · Issue #1701 · exercism/v3](https://github.com/exercism/v3/issues/1701)
> [Clojure] config.json: add lists, and minor update in doc

- languages/c/reference/README.md
A few extra concepts found in the v2 concept extractions
- Add:
- ptrdiff_t
- size_t
- Void 
- Fixed width integer types
- Remove:
- Typedef (already covered by Renaming Types)
> [C] Update concepts list

- languages/common-lisp/bin/generate-scaffolding/template/.meta/config.json
The template file for `.meta/config.json` was empty. This PR adds some default contents.
> [Common Lisp] Add some template contents for .meta/config.json

- languages/go/exercises/concept/slices/slices.go
- languages/go/exercises/concept/slices/slices_test.go
- languages/go/exercises/concept/strings/strings.go
- languages/go/exercises/concept/strings/strings_test.go
I think this got overlooked when we renamed the exercise. Having a _ in the name of a package does not fit well in Go.
> [Go] Change name of packages

- languages/common-lisp/bin/generate-scaffolding/template/.meta/example.lisp
This is a new PR so we can just get it merged quickly
> [Common Lisp] Remove some angle-brackets left behind in a template file

- languages/csharp/exercises/concept/basics/.docs/after.md
- languages/csharp/exercises/concept/basics/.docs/introduction.md
The current `introduction.md` and `after.md` documents of the `basics` actually contains invalid code, as in it uses a `static` method call which should be an instance call.
> [C#] Add new object mention in basics introduction

- languages/ruby/config.json
- languages/ruby/exercises/concept/README.md
- languages/ruby/exercises/concept/numbers/.docs/after.md
- languages/ruby/exercises/concept/numbers/.docs/introduction.md
- languages/ruby/exercises/concept/numbers/.meta/config.json
- languages/ruby/exercises/concept/numbers/.meta/design.md
From https://github.com/exercism/v3/issues/2046:
- Make `booleans` a prerequisite of `numbers` -> Done
- Remove Boolean-content from `numbers`, ensure the content appears in `booleans` -> Done (at least I think so). The content I removed here is covered in the [introduction.md](https://github.com/exercism/v3/blob/master/languages/ruby/exercises/concept/booleans/.docs/introduction.md) of the booleans exercise.
Please let me know if I missed something, thanks.
> Ruby remove booleans from numbers

- languages/go/config.json
@ErikSchierboom: I removed the float dependency from strings again. Even though we format a float value in there it just doesn't fit in the general context of exercises. The strings exercise would be available at `basics` > `numbers` > `floating-points` > `strings`. With that the whole point of an early strings exercise is gone, again. I'd rather have a small paragraph on floats in the intro, instead.
> [Go] config file

- languages/common-lisp/config.json
This is so we can have a nice looking tree on https://v3.exercism.io/common-lisp/maintaining/tree (which is actually broken at the moment, but should be fixed soon).
Think something like: https://v3.exercism.io/go/maintaining/tree
> [Common Lisp] Add empty exercises to fill in dashboard tree

- .github/workflows/valid-files.yml
See #2087 for an example for why this is needed.
> [CI] Exclude auto-generated Markdown files from file limit check

- languages/go/exercises/concept/basics/.docs/instructions.md
- languages/go/exercises/concept/booleans/.docs/after.md
- languages/go/exercises/concept/methods/.docs/instructions.md
- languages/go/exercises/concept/slices/.docs/instructions.md
- languages/go/exercises/concept/strings-package/.docs/instructions.md
- languages/go/exercises/concept/strings/.docs/instructions.md
- languages/go/exercises/concept/structs/.docs/instructions.md
- languages/go/exercises/concept/time/.docs/instructions.md
I chose to use `Output:` as formatting. Please let me know if this is alright.
> [Go] change output formatting in examples comments #2010

- languages/rust/reference/merge-strategy.md
~~See #1725 for the backstory.~~
@coriolinus and I met 2 weeks ago to clarify our approach to a merge policy.
We decided to proceed as follows:
1. write down our current Pessimistic Merging policy
2. propose an Optimistic Merging approach with a bounded duration to increase contribution efficiency before the v3 launch
3. return to a Pessimistic Merging policy upon V3 launch.
I have revised this PR to solve the first step. I'll author a subsequent PR with the OM proposals so we can come to consensus on what that looks like before rushing ahead.
> [Docs] begin the Rust track's merging guidelines document

- languages/csharp/exercises/concept/strings/.meta/Example.cs
> [C#] fix LogLevel method in Strings Concept exercise

- languages/rust/reference/README.md
Any work should be itemized as GitHub issue so we can delegate
appropriately and have an idea of what is left. Given our need to
complete more concept exercises I have removed this list. The general
tasks can be included as part of our contribution guide or itemized as
other issues.
Closes #1023.
> [Docs] remove TODOs from Rust reference

- languages/ruby/exercises/concept/basics/lasagna.rb
- languages/ruby/exercises/concept/booleans/.docs/instructions.md
- languages/ruby/exercises/concept/booleans/attendee.rb
- languages/ruby/exercises/concept/instance-variables/.docs/hints.md
- languages/ruby/exercises/concept/instance-variables/.docs/instructions.md
- languages/ruby/exercises/concept/instance-variables/attendee.rb
**Issue**: https://github.com/exercism/v3/issues/2055
**Description**
As per the issue description, this PR normalizes the naming for method references to `<CLASS>.<METHOD>` for class methods and `<CLASS>#<METHOD>` for instance methods.
> [Ruby] Normalize naming for method references

- languages/haskell/reference/implementing-a-concept-exercise.md
Note: This is not for Hacktoberfest. I was just reading and saw this typo
(although I wouldn't mind it counting. I will probably hit the min with exercise anyways)
> [Haskell] Docs: change case of `haskell` directory

- languages/elixir/exercises/concept/protocols/.docs/after.md
- languages/elixir/exercises/concept/protocols/.docs/hints.md
- languages/elixir/exercises/concept/protocols/.docs/instructions.md
- languages/elixir/exercises/concept/protocols/.docs/introduction.md
- languages/elixir/exercises/concept/protocols/.formatter.exs
- languages/elixir/exercises/concept/protocols/.gitignore
- languages/elixir/exercises/concept/protocols/.meta/config.json
- languages/elixir/exercises/concept/protocols/.meta/design.md
- languages/elixir/exercises/concept/protocols/.meta/example.ex
- languages/elixir/exercises/concept/protocols/lib/rpg.ex
- languages/elixir/exercises/concept/protocols/mix.exs
- languages/elixir/exercises/concept/protocols/test/rpg_test.exs
- languages/elixir/exercises/concept/protocols/test/test_helper.exs
This is my idea for the concept exercise about protocols. The draft includes the instructions, tests, and a sample solution.
> [Elixir] New concept exercise - `protocols`

- languages/ruby/exercises/concept/strings/.docs/instructions.md
It now follows the same format as the other instruction files for Ruby.
Fix as discussed here: https://github.com/exercism/v3/issues/2055#issuecomment-702999038
> [Ruby] Update log line level instructions

- .github/workflows/labeler.yml
This allows labeler to label PRs from forks.
`pull_request_target` runs workflows within the target repo of a PR rather than the source repo. Since labeler only acts on meta-info of the PR event rather than code included in the PR, this is safe to run.
See also the updated docs: https://github.com/actions/labeler#create-workflow
> [CI] Trigger labeler on pull_request_target event

- languages/c/config.json
- languages/clojure/config.json
- languages/common-lisp/config.json
- languages/cpp/config.json
- languages/csharp/config.json
- languages/dart/config.json
- languages/elixir/config.json
- languages/elm/config.json
- languages/emacs-lisp/config.json
- languages/erlang/config.json
- languages/fsharp/config.json
- languages/go/config.json
- languages/haskell/config.json
- languages/j/config.json
- languages/java/config.json
- languages/javascript/config.json
- languages/julia/config.json
- languages/kotlin/config.json
- languages/nim/config.json
- languages/perl5/config.json
- languages/purescript/config.json
- languages/python/config.json
- languages/ruby/config.json
- languages/rust/config.json
- languages/scala/config.json
- languages/swift/config.json
- languages/x86-64-assembly/config.json
As per the [updated specification](https://github.com/exercism/v3/issues/2293), this PR adds a top-level "concepts" section to each track's `config.json` file. The `name` property is inferred from the slug, but could use some tweaking here and there. Individual tracks can do this themselves once this merged. The same goes for the `blurb` property, which has just some placeholder TODO text.
I'll update the documentation in a separate PR.
> [All] Add concepts section to config.json

- languages/c/config.json
- languages/clojure/config.json
- languages/common-lisp/config.json
- languages/cpp/config.json
- languages/csharp/config.json
- languages/dart/config.json
- languages/elixir/config.json
- languages/elm/config.json
- languages/emacs-lisp/config.json
- languages/erlang/config.json
- languages/fsharp/config.json
- languages/go/config.json
- languages/haskell/config.json
- languages/j/config.json
- languages/java/config.json
- languages/javascript/config.json
- languages/julia/config.json
- languages/kotlin/config.json
- languages/nim/config.json
- languages/perl5/config.json
- languages/purescript/config.json
- languages/python/config.json
- languages/ruby/config.json
- languages/rust/config.json
- languages/scala/config.json
- languages/swift/config.json
- languages/x86-64-assembly/config.json
This PR adds the existing v2 exercises of all tracks to the v3 tracks' config.json files (see https://github.com/exercism/v3/issues/2293). It does this by copying the original exercise but with some changes:
- The `core`, `auto_approve` and `unlocked_by` keys are removed. They are no longer relevant in v3.
- A `prerequisites` key is added. This key will have the same function as the `prerequisites` key for concept exercise: it determines when the exercise is unlocked.
- The `topics` property is also copied. Its goal is to help with populating the prerequisites property. The `topics` property has no value in v3 and we'll remove it once the prerequisites property has been populated.
I've added a separate commit per language to make reviews easier. It might also be nice to not squash this on …
> Add practice exercises

- languages/rust/concepts/enums-basic/about.md
- languages/rust/concepts/enums-basic/links.json
- languages/rust/exercises/concept/enums/.docs/after.md
```
<track>
├── concepts
│   └── ...
```
1. Extract the …
> [Rust] enums - replace about.md file with concept files

- languages/julia/concepts/multiple-dispatch/about.md
- languages/julia/concepts/multiple-dispatch/links.json
- languages/julia/exercises/concept/multiple-dispatch/.docs/after.md
```
<track>
├── concepts
│   └── ...
```
1. Extract the …
> [Julia] multiple-dispatch - replace about.md file with concept files

- languages/csharp/concepts/exceptions/about.md
- languages/csharp/exercises/concept/exceptions/.docs/after.md
```
<track>
├── concepts
│   └── ...
```
1. Extract the …
> [C#] exceptions - replace about.md file with concept files

- languages/elixir/concepts/lists/about.md
A fix for https://github.com/exercism/v3/issues/2520.
Probably I'm not too sure about `appending to a list in a loop is an anti-pattern, prepend and reverse instead` bit since I've been thinking mostly in terms of list comprehensions. I've still add some explanation around it.
Open to make the changes based on any feedback.
> Update documentation for Lists.

- languages/go/concepts/errors/about.md
- languages/go/exercises/concept/errors/.docs/after.md
```
<track>
├── concepts
│   └── ...
```
1. Extract the …
> [Go] errors - replace about.md file with concept files

- .github/workflows/csharp-exercise-report.yml
- .github/workflows/julia-exercise-ci.yml
- .github/workflows/labeler.yml
- .github/workflows/nim-ci.yml
- .github/workflows/update-summary-concepts.yml
- .github/workflows/update-summary-languages.yml
- .github/workflows/update-summary-stories.yml
- .github/workflows/valid-files.yml
- .github/workflows/valid-links.yml
- .github/workflows/verify-code-formatting.yml
- .github/workflows/verify-csharp-formatting.yml
Some PRs like #2537 have a lot of checks. The check overview can get quite messy.
This PR renames all workflows/checks to follow the same scheme:
`category / name`
where `category` is currently `CI` (general checks like the file checks), `Tools` (Things like the summary generators, labeler) and track names.
The downside is that the detailed view and Action tab become less readable:
Personally I think the PR/Commit popup view are more important because they're the main thing one sees, so IMO this trade off is worth it.
---
Note that this will require changing the required checks to the new names (@iHiD)
> [CI] Rename workflows/builds to tidy up check view

- .github/workflows/valid-links.yml
This updates the markdown link checker to check all the files instead of just exiting after the first one that fails
closes #2538
> [CI] Update dead links check to check all files

- languages/csharp/exercises/concept/structs/StructsTests.cs
Used reflection to invoke plot constructor or throw error if not found.  This allows the code to build out of the box instead of having build errors
Fixes #1846 
Maintainers - can you add the hacktoberfest-accepted label to my PR?  Thank you
> [C#] Fix Struct Tests to build out of the box.

- languages/elixir/config.json
When renaming exercises, I made a mistake in the config with the `numbers` exercise and named it `rpn-calculator` instead its real name, `freelancer-rates`. This PR fixes that issue, plus adds pretty names for exercises whose slug cannot be simply title-cased.
> [Elixir] Fix numbers (freelancer-rate) exercise name; Add pretty names where necessary

- languages/go/exercises/concept/methods/.meta/config.json
- languages/go/exercises/concept/strings/.meta/config.json
- languages/go/exercises/concept/structs/.meta/config.json
For some reason these three files had `U+FEFF` symbols at the start, which breaks some JSON libraries. This removes those.
You can see the char in the GitHub web editor. Locally checked out files, at least on my machine, didn't seem to have them.
----
The failed check is expected, see #2617
> [Go] Remove invisible chars in .meta/config.json

- bin/format.cmd
- bin/format.sh
Looks like when #2619 was merged it updated only the versions of
prettier in use by the GitHub Actions not that of those used by
`./bin/format.{sh,cmd}`.
This commit sets the version of prettier used by the latter to be equal of
Without this change the scripts will produce a lot of copies of the
following message:
`[warn] Ignored unknown option { embeddedLanguageFormatting: "auto" }.`
----
#
> Update prettier version used in format scripts.

- languages/common-lisp/concepts/cons/about.md
- languages/common-lisp/concepts/cons/links.json
- languages/common-lisp/concepts/lists/about.md
- languages/common-lisp/concepts/lists/links.json
- languages/common-lisp/config.json
- languages/common-lisp/exercises/concept/leslies-lists/.docs/introduction.md
```
<track>
├── concepts
│   └── ...
```
1. Extract the …
> [Common Lisp] lists - replace about.md file with concept files

- languages/purescript/concepts/booleans/about.md
- languages/purescript/exercises/concept/booleans/.docs/after.md
```
<track>
├── concepts
│   └── ...
```
1. Extract the …
> [PureScript] booleans - replace about.md file with concept files

- languages/python/concepts/basics/about.md
- languages/python/concepts/basics/links.json
- languages/python/exercises/concept/guidos-gorgeous-lasagna/.docs/introduction.md
- Edited `introduction.md` and `about.md` to contain reference links instead of in-line links
- Edited `introduction.md` down to only include examples needed for exercise.
- Edited `links.json` to shorten it.
> [Python] Basics Concept Exercise Reformat - A Re-implementation of PR 2534

- languages/python/concepts/strings/about.md
*  Changed the in-Text links in the `about.md` string concept to reference links at the bottom of the doc.
*  Additionally edited the code examples to render correctly - some code blocks were causing issues in the markdown.
> [Python] Strings Concept: Changed in-Text Links to Ref Links

- languages/csharp/exercises/concept/red-vs-blue-darwin-style/.meta/Example.cs
- languages/csharp/exercises/concept/red-vs-blue-darwin-style/.meta/config.json
- languages/csharp/exercises/concept/red-vs-blue-darwin-style/RedVsBlueDarwinStyle.cs
- languages/csharp/exercises/concept/red-vs-blue-darwin-style/RedVsBlueDarwinStyleTests.cs
- Removed using Combined from Tests
- Added tests based on the type
I did not add any unit tests for the aliases Red/Blue.
Closes #2026
> [C#] Namespace concept. Red vs Blue. Tests

- languages/csharp/exercises/concept/booking-up-for-beauty/.meta/config.json
- languages/csharp/exercises/concept/booking-up-for-beauty/BookingUpForBeautyTests.cs
- use constructor/destructor instead of the attribute for en-us culture in the tests
Closes #1811
> [C#] datetimes. Constructor for test culture en us

- languages/rust/scripts/test_pr.sh
The v3 repo doesn't automatically test PRs for Rust compilation or tests,
so we need a simple way to manage that locally. This script does that.
For every rust concept exercise in a PR, it downloads the source
and tests files, tests the exercise, then cleans up.
Inspiration: https://github.com/exercism/v3/pull/2522#issuecomment-730313267
> [rust]: add script to test a pull request

- languages/common-lisp/exercises/concept/key-comparison/.meta/example.lisp
- languages/common-lisp/exercises/concept/leslies-lists/.meta/example.lisp
- languages/common-lisp/exercises/concept/pal-picker/.meta/example.lisp
- languages/common-lisp/exercises/concept/pizza-pi/.meta/example.lisp
- languages/common-lisp/exercises/concept/socks-and-sexprs/.meta/example.lisp
When the exercises were renamed the renaming did not extend to the
`example.lisp` files so they were no longer correct examples of
solutions to the problems.
> [Common Lisp] Fix package declarations in exercise example files

- languages/python/exercises/concept/log-levels/.docs/instructions.md
I've found a word "defind" on document and I think it is mistyped and originally intended to write "define".
> Fix typo in line 27, from defind to define

- .github/markdown-link-check-config.json
This file belonged to the old markdown link checker which we no longer use.
> [CI] Remove unused markdown link check config file

- languages/common-lisp/exercises/concept/leslies-lists/.docs/instructions.md
- languages/common-lisp/exercises/concept/pal-picker/.docs/instructions.md
- languages/common-lisp/exercises/concept/pizza-pi/.docs/instructions.md
- languages/common-lisp/exercises/concept/socks-and-sexprs/.docs/hints.md
- languages/common-lisp/exercises/concept/socks-and-sexprs/.docs/instructions.md
Given our lack of understanding of Lisp Alien biology and societal norms it is best to use gender neutral pronouns for them for the time being until we get to know them better.
----
Fixes #2855
> [Common Lisp] Using gender neutral pronouns for Lisp Aliens.

- .github/workflows/valid-links.yml
The previous issue was fixed in https://github.com/ErikSchierboom/MarkdownLinkChecker/pull/11
> [CI] Enable external link checks

- languages/python/concepts/string-methods/about.md
- Fix `https:/` to `https://`
- startswith typo
> [Python] str-methods. Fix https prefix and typo

- languages/elixir/config.json
A quick comparison of the concepts in the config and the directories inside `elixir/concepts` revealed two missing concepts.
> [Elixir] Add concepts missing in the config

- languages/fsharp/exercises/concept/booking-up-for-beauty/.meta/config.json
- languages/fsharp/exercises/concept/cars-assemble/.meta/config.json
- languages/fsharp/exercises/concept/interest-is-interesting/.meta/config.json
- languages/fsharp/exercises/concept/lucians-luscious-lasagna/.meta/config.json
This turns the other half of tests on master green and would allow us to set this check to required so that no new exercises can be added anymore unless they create at least stubs for the concepts files.
It'll save us all dozens of build failure notifications as a nice side effect ;)
> Make meta-config files check pass

- bin/format.sh
This should prevent surprises for anyone else manually invoking
./bin/format.sh
> inform user of environment dependency

- languages/rust/scripts/test_pr.sh
It looks like BSD's `mktemp` does not support the long option
`--directory`. But GNU's supports the `-d`. So I updated the script to
use `-d`.
The sweet smell of cross-platform utilities!
> [Rust] patch test_pr.sh for BSD mktemp

- languages/python/concepts/lists/about.md
There are words that are not referenced, so I added the appropriate link I think.
If these are not appropriate, let me know. I'll fix it :)
> [Python] add link design.md

- languages/elixir/exercises/concept/rpn-calculator-output/test/rpn_calculator/output_test.exs
In case of this exercise, it's not entirely possible to make them fully self-contained because of the need for a test module that implements the `open` and `close` functions. This has to be good enough 🤷
> [Elixir] Ensure that tests are self-contained - `rpn-calculator-output`

- languages/elixir/concepts/charlists/about.md
- languages/elixir/concepts/ranges/about.md
- languages/elixir/config.json
- languages/elixir/exercises/concept/chessboard/.docs/hints.md
- languages/elixir/exercises/concept/chessboard/.docs/instructions.md
- languages/elixir/exercises/concept/chessboard/.docs/introduction.md
- languages/elixir/exercises/concept/chessboard/.formatter.exs
- languages/elixir/exercises/concept/chessboard/.gitignore
- languages/elixir/exercises/concept/chessboard/.meta/config.json
- languages/elixir/exercises/concept/chessboard/.meta/design.md
- languages/elixir/exercises/concept/chessboard/.meta/example.ex
- languages/elixir/exercises/concept/chessboard/lib/chessboard.ex
- languages/elixir/exercises/concept/chessboard/mix.exs
- languages/elixir/exercises/concept/chessboard/test/chessboard_test.exs
- languages/elixir/exercises/concept/chessboard/test/test_helper.exs
- languages/elixir/exercises/concept/date-parser/.docs/introduction.md
- languages/elixir/exercises/concept/dna-encoding/.docs/hints.md
- languages/elixir/exercises/concept/dna-encoding/.docs/instructions.md
- languages/elixir/exercises/concept/dna-encoding/lib/dna.ex
- languages/elixir/exercises/concept/dna-encoding/test/dna_test.exs
- languages/elixir/exercises/concept/mensch-aergere-dich-nicht/.docs/hints.md
- languages/elixir/exercises/concept/mensch-aergere-dich-nicht/.docs/introduction.md
- languages/elixir/exercises/concept/mensch-aergere-dich-nicht/.meta/design.md
- languages/elixir/reference/README.md
- languages/elixir/reference/exercise-concepts/pangram.md
- languages/elixir/reference/exercise-concepts/rna-transcription.md
As I mentioned in https://github.com/exercism/v3/pull/2876, introducing `randomness` in an exercise that requires `ranges` (`captains-log`) is not great because the exercise that taught `ranges` so far also used a bit of `randomness` (`mensch-aergere-dich-nicht`). To remove that (weak) circular dependency, I want to introduce an exercise that will teach just `ranges` and will come before the other two.
> [Elixir] Propose a simple chessboard `ranges` exercise

- languages/elixir/exercises/concept/kitchen-calculator/.meta/example.ex
- languages/elixir/exercises/concept/kitchen-calculator/test/kitchen_calculator_test.exs
This PR removes the module alias and runs `mix_format`.
> [Elixir] Ensure that tests are self-contained - `kitchen-calculator`

- languages/elixir/exercises/concept/language-list/test/language_list_test.exs
This PR:
- removes a module alias 
- removes module attributes
- removes the usage of the word list sigil so that understanding the test doesn't require knowing that feature
> [Elixir] Ensure that tests are self-contained - `language-list`

- languages/elixir/exercises/concept/remote-control-car/.meta/example.ex
- languages/elixir/exercises/concept/remote-control-car/test/remote_control_car_test.exs
This PR removes the usage of a module attribute and runs `mix format`.
> [Elixir] Ensure that tests are self-contained - `remote_control_car`

- languages/javascript/concepts/nullability/about.md
```
<track>
├── concepts
│   └── ...
```
1. Extract the …
> [JavaScript] nullability - replace about.md file with concept files

- languages/javascript/concepts/booleans/about.md
- languages/javascript/concepts/booleans/links.json
- languages/javascript/exercises/concept/booleans/.docs/after.md
```
<track>
├── concepts
│   └── ...
```
1. Extract the …
> [JavaScript] booleans - replace about.md file with concept files

- languages/common-lisp/concepts/default-parameters/about.md
- languages/common-lisp/concepts/default-parameters/links.json
- languages/common-lisp/concepts/functions/about.md
- languages/common-lisp/concepts/lambda-list/about.md
- languages/common-lisp/concepts/lambda-list/links.json
- languages/common-lisp/concepts/named-parameters/about.md
- languages/common-lisp/concepts/named-parameters/links.json
- languages/common-lisp/concepts/rest-parameters/about.md
- languages/common-lisp/concepts/rest-parameters/links.json
- languages/common-lisp/config.json
- languages/common-lisp/exercises/concept/lillys-lasagna-leftovers/.docs/hints.md
- languages/common-lisp/exercises/concept/lillys-lasagna-leftovers/.docs/instructions.md
- languages/common-lisp/exercises/concept/lillys-lasagna-leftovers/.docs/introduction.md
- languages/common-lisp/exercises/concept/lillys-lasagna-leftovers/.meta/config.json
- languages/common-lisp/exercises/concept/lillys-lasagna-leftovers/.meta/design.md
- languages/common-lisp/exercises/concept/lillys-lasagna-leftovers/.meta/example.lisp
- languages/common-lisp/exercises/concept/lillys-lasagna-leftovers/lillys-lasagna-leftovers-test.lisp
- languages/common-lisp/exercises/concept/lillys-lasagna-leftovers/lillys-lasagna-leftovers.lisp
As a follow-up to #2851 this PR adds a concept exercise to teach further function related concepts such as:
- `&key` parameters
- `&optional` parameters
- `&rest` parameters
> [Common Lisp] Concept Exercise: Lilly's Lasagna Leftovers

- languages/go/concepts/strings-package/about.md
- languages/go/exercises/concept/strings-package/.docs/after.md
```
<track>
├── concepts
│   └── ...
```
1. Extract the …
> [Go] strings-package - replace about.md file with concept files

- languages/elixir/exercises/concept/high-score/.docs/hints.md
- languages/elixir/exercises/concept/high-score/.docs/instructions.md
- languages/elixir/exercises/concept/high-score/.meta/example.ex
- languages/elixir/exercises/concept/high-score/lib/high_score.ex
- languages/elixir/exercises/concept/high-score/test/high_score_test.exs
Issue: https://github.com/exercism/v3/issues/2513
I'm replacing the last two steps that used `Enum` with a single simple step that uses `Map.keys`.
> [Elixir] Remove usage of `enum` (a later concept) from the `maps` exercise

- languages/ruby/concepts/strings/about.md
- languages/ruby/concepts/strings/links.json
- languages/ruby/exercises/concept/strings/.docs/after.md
```
<track>
├── concepts
│   └── ...
```
1. Extract the …
> [Ruby] strings - replace about.md file with concept files

- languages/elixir/concepts/tuples/introduction.md
- languages/elixir/exercises/concept/kitchen-calculator/.docs/hints.md
- languages/elixir/exercises/concept/kitchen-calculator/.docs/instructions.md
- languages/elixir/exercises/concept/kitchen-calculator/.docs/introduction.md
- languages/elixir/exercises/concept/kitchen-calculator/.meta/example.ex
- languages/elixir/exercises/concept/kitchen-calculator/lib/kitchen_calculator.ex
- languages/elixir/exercises/concept/kitchen-calculator/test/kitchen_calculator_test.exs
According to https://github.com/exercism/v3/blob/9f44de6bda78086709ce345e3b5b12dd7c8b5a49/docs/maintainers/style-guide.md#language all content needs to be AmE, so I changed "millilitre" to "milliliter". I also rephrased the instructions not to use lists (to be consistent with instructions for other exercises), and I removed examples of input values from the paragraphs because examples belong in code snippets.
> [Elixir] Improve exercise `kitchen-calculator`

- languages/elixir/concepts/lists/introduction.md
- languages/elixir/exercises/concept/language-list/.docs/introduction.md
String literals were added to the `basics` (https://github.com/exercism/v3/commit/d9a84126c0e7aee415804d20d58d58fd1d31f915) concept so they don't need to be mentioned again for `lists`
> [Elixir] Remove mention of string literals from lists

- languages/elixir/exercises/concept/language-list/.docs/instructions.md
I noticed that the function names in the last two steps were incorrect, so I'm fixing that. I also split each function call into its own line so that it's easier to read on the website on a narrower screen, and I extended the code snippets a bit to better show that the languages are prepended to the list, not appended.
> [Elixir] Improve `language-list` instructions code snippets

- languages/common-lisp/exercises/concept/key-comparison/key-comparison-test.lisp
This PR mainly adds descriptions to each test. While doing this it seemed a good idea to split a few tests up to be more granular (_e.g._ splitting testing character equality apart from the case-insensitive version).
Fixes #2967
> [Common Lisp] Improving test/test descriptions in key-comparison exercise

- languages/common-lisp/concepts/comments/introduction.md
- languages/common-lisp/concepts/conditionals/introduction.md
- languages/common-lisp/concepts/expressions/introduction.md
- languages/common-lisp/concepts/floating-point-numbers/introduction.md
- languages/common-lisp/concepts/lambda-list/introduction.md
- languages/common-lisp/concepts/sameness/introduction.md
- languages/common-lisp/concepts/symbols/introduction.md
This PR presents some mostly small tweaks to the generated concept introduction files to hopefully make them more suitable.
The largest change was for the lambda list concept which didn't have a properly formatted section in the exercise's introduction.md to begin with.
This PR does not pretend to fix all problems with the concepts' introduction files, it is only intended to make a first pass after they were generated to bring them up to a first or second draft level of quality.
Fixes #2973.
> [Common Lisp] Review generated concept introductions

- languages/go/concepts/conditionals/about.md
- languages/go/concepts/conditionals/links.json
- languages/go/concepts/numbers/about.md
- languages/go/concepts/numbers/links.json
- languages/go/exercises/concept/numbers/.docs/after.md
```
<track>
├── concepts
│   └── ...
```
1. Extract the …
> [Go] numbers - replace about.md file with concept files

- languages/elixir/concepts/try-rescue/introduction.md
- languages/elixir/exercises/concept/rpn-calculator/.docs/instructions.md
- languages/elixir/exercises/concept/rpn-calculator/.docs/introduction.md
- languages/elixir/exercises/concept/rpn-calculator/.meta/example.ex
The only detail that this exercise was missing was any sort of hint for the last step about what is the "error message" and how to get it. The exception protocol only comes after this exercise, that's why I decided to add this information only as a casual mention in the instructions.
> [Elixir] Improve exercise `rpn-calculator`

- languages/elixir/concepts/basics/about.md
- languages/elixir/concepts/basics/introduction.md
- languages/elixir/concepts/basics/links.json
- languages/elixir/exercises/concept/lasagna/.docs/introduction.md
As I was going through our track on exercism.lol trying to feel like a student, I kept thinking that all of the hints and explanations link to the documentation and mention the Kernel module without any introduction first what that actually is.
To solve this issue, I extended the `basics` concept to shortly explain the standard library.
> [Elixir] Extend the `basics` concept to mention the standard library

- languages/elixir/concepts/bitstrings/introduction.md
- languages/elixir/concepts/tail-call-recursion/introduction.md
- languages/elixir/exercises/concept/dna-encoding/.docs/hints.md
- languages/elixir/exercises/concept/dna-encoding/.docs/instructions.md
- languages/elixir/exercises/concept/dna-encoding/.docs/introduction.md
- languages/elixir/exercises/concept/dna-encoding/.meta/example.ex
- languages/elixir/exercises/concept/dna-encoding/test/dna_test.exs
This PR includes:
- `mix format`
- Removing any mention of `Enum` because this exercise doesn't have a dependency on that concept, and technically doesn't need to. `Enum.reverse` can be easily replaced by a tail-recursive function, exactly the topic of this exercise!
- Some rewording of the instructions
> [Elixir] Improve exercise `dna-encoding`

- languages/elixir/concepts/regular-expressions/introduction.md
- languages/elixir/exercises/concept/date-parser/.docs/hints.md
- languages/elixir/exercises/concept/date-parser/.docs/instructions.md
- languages/elixir/exercises/concept/date-parser/.docs/introduction.md
- languages/elixir/exercises/concept/date-parser/test/date_parser_test.exs
This PR, among other changes, includes two additions to the test suite.
- Added tests for `month_names` and `day_names` that will detect if write `"Sunday|Monday|Tuesday|Wednesday|Thursday|Friday|Saturday"` instead of `"(Sunday|Monday|Tuesday|Wednesday|Thursday|Friday|Saturday)"` regardless of the order of the days/months. There was a check for something like that with the "combined" assertion that it doesn't match "SundayMonday", but that would only detect this problem if you start listing the days from Sunday. In many places you start with Monday, and chaotic people might even write it out of order :).
- Added tests for `match_` that will detect if somebody forgot to use `^` and `$`. It's required according to the examples given for this step in the instructions.
> [Elixir] Improve exercise `date-parser`

- languages/elixir/concepts/dynamic-dispatch/introduction.md
- languages/elixir/exercises/concept/rpn-calculator-output/.docs/instructions.md
- languages/elixir/exercises/concept/rpn-calculator-output/.docs/introduction.md
In this PR, I want to change two things:
- Remove a code example from the introduction that doesn't show new syntax.
- Rephrase the instructions to consistently call the value returned by `resource.open` an "IO device" instead of mixing up "IO device", "file", and "handler".
> [Elixir] Improve exercise `rpn-calculator-output`

- languages/elixir/concepts/access-behaviour/about.md
- languages/elixir/concepts/access-behaviour/introduction.md
- languages/elixir/concepts/exceptions/introduction.md
- languages/elixir/concepts/structs/about.md
- languages/elixir/concepts/structs/introduction.md
- languages/elixir/exercises/concept/basketball-website/.docs/hints.md
- languages/elixir/exercises/concept/basketball-website/.docs/introduction.md
- languages/elixir/exercises/concept/basketball-website/.meta/design.md
- languages/elixir/exercises/concept/remote-control-car/.docs/introduction.md
- languages/elixir/exercises/concept/stack-underflow/.docs/hints.md
- languages/elixir/exercises/concept/stack-underflow/.docs/instructions.md
- languages/elixir/exercises/concept/stack-underflow/.docs/introduction.md
- languages/elixir/exercises/concept/stack-underflow/test/rpn_calculator/exception_test.exs
This PR:
- Changes the spelling of "behavior" to "behaviour" when talking about the Elixir concept.
- Adds more test cases so it's clear which error to raise when the stack has only one number, and when that number is a zero.
- Adds a hint that modules can be nested. I think this didn't pop up anywhere.
> [Elixir] Improve exerecise `stack underflow`

- languages/elixir/exercises/concept/date-parser/lib/date_parser.ex
- languages/elixir/exercises/concept/dna-encoding/lib/dna.ex
- languages/elixir/exercises/concept/guessing-game/.meta/example.ex
- languages/elixir/exercises/concept/guessing-game/test/guessing_game_test.exs
- languages/elixir/exercises/concept/high-score/lib/high_score.ex
- languages/elixir/exercises/concept/kitchen-calculator/lib/kitchen_calculator.ex
- languages/elixir/exercises/concept/log-level/.docs/hints.md
- languages/elixir/exercises/concept/log-level/.docs/instructions.md
- languages/elixir/exercises/concept/log-level/.meta/example.ex
- languages/elixir/exercises/concept/log-level/lib/log_level.ex
- languages/elixir/exercises/concept/log-level/test/log_level_test.exs
- languages/elixir/exercises/concept/stack-underflow/.meta/example.ex
The problem with the `cond` expression is that it is only necessary if you have at least 2 different input variables and 3 different output values. If there is a single input, it's easier to use `case`. If there are only 2 output values, it's easier to use `if`. Then I solved the exercise in its original form spontaneously, I did it like this, without `cond`.
```elixir
defmodule LogLevel do
def to_label(level) do
case level do
0 -> :trace
1 -> :debug
4 -> :info
5 -> :warning
6 -> :error
7 -> :fatal
_ -> :unknown
end
end
def send_alert?(level) do
label = to_label(level)
label in [:fatal, :error, :unknown]
end
end
```
To steer people into using `cond`, I'm proposing a change to the exercise that introduces the concept of a "legacy app" that doesn't support all log codes, and changing …
> [Elixir] Extend the `log-level` exercise to justify using `cond` over `if` or `case`
