languages/ruby/README.md
Hello, I'm following instructions from the slack channel and opening my first PR 😉
=> Remove extra bracket

languages/go/maintainers.md
@ErikSchierboom: I liked the link to the github profile. Hope that is ok.
=> Add tehsphinx to Go Track maintainer

languages/emacs-lisp/README.md, languages/emacs-lisp/docs/implementing-a-concept-exercise.md, languages/emacs-lisp/maintainers.md
Emacs lisp maintainer here getting caught up on the v3 migration. Just getting things going for Elisp in v3. 👋
=> Bootstrap Emacs Lisp track

README.md
I'm presuming this will be merged straight into master but I believe this is right for this change.
Cheers!
=> #53 Added Elixir issue search to the README

README.md
=> Add Ruby issue search link to Readme

languages/c/maintainers.md
Think that's everyone so far now :)
=> Add senior maintainers

README.md
Per Preparation Status in [v3/languages/C.README.md](https://github.com/exercism/v3/blob/5b0f48f845420a953814d4d62696c8b8b4b6f6f9/languages/c/README.md)
=> Add link to C issues

languages/javascript/README.md, languages/javascript/config.json
Added to the `config.json`:
```javascript
"online_editor": {
"indent_style": "space",
"indent_size": 2
},
```
and updated README to reflect the current status of the config.json update
=> [JavaScript] Added online editor settings to config.json

languages/c/maintainers.md
Correcting the typo in the names.
=> C: Update the github profile link names.

languages/javascript/maintainers.md, languages/python/maintainers.md
=> Add paparomeo to Python and Javascript maintainers

README.md
It seems that some people guess that this list is sorted alphabetically and others don't, and every time people don't they're asked to sort it alphabetically. So maybe placing a comment will save a few requests.
=> README.md: Remark that list is sorted alphabetically.

languages/purescript/README.md, languages/purescript/docs/implementing-a-concept-exercise.md, languages/purescript/maintainers.md
=> [PureScript] Bootstrap track

languages/README.md, languages/cpp/README.md, languages/cpp/docs/implementing-a-concept-exercise.md, languages/cpp/maintainers.md
Not quite sure if this is the proper process but figured we could get this language added as well.
=> [C++] Adding in C++ language track

docs/maintainers/repository-structure.md
@tehsphinx Perhaps this makes the labels a bit more clear?
=> [Docs] clarify labels

languages/javascript/maintainers.md
Hi there! I'm Ayato from Japan. I'm a new maintainer of JavaScript track.
I'm happy to be part of this community.
Thanks to Exercism I learned a lot about JavaScript, so I want to give back to.
👋
=> Add Ayato Hayashi to JavaScript maintainers

languages/javascript/maintainers.md
- Add both senior and active maintainers for the JavaScript track
- Sort all maintainers alphabetically
=> [JavaScript] Add senior maintainers and sort alphabetically

languages/elixir/README.md, languages/elixir/config.json
Skeleton file after following instructions at:
https://github.com/exercism/v3/blob/master/docs/maintainers/migrating-your-config-json-files.md
=> [Elixir] v3 config.json

docs/maintainers/_sidebar.md, docs/maintainers/website.md
Add information how to run the website locally
=> [Docs] Add documentation explaining how to run website locally

.github/workflows/rebase.yml
See https://github.com/exercism/v3/pull/135#issuecomment-575354375 and/or https://julienrenaux.fr/2019/12/20/github-actions-security-risk/
=> Pin rebase action to commit hash

languages/elixir/maintainers.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/exercism/v3/117)
=> [Elixir] Add filalex77 to Contributing Maintainers

languages/elixir/config.json
=> [Elixir] Remove "foregone" property from config.json

languages/rust/README.md, languages/rust/docs/implementing-a-concept-exercise.md, languages/rust/maintainers.md
=> [Rust] Bootstrap

README.md, languages/clojure/README.md, languages/clojure/docs/implementing-a-concept-exercise.md, languages/clojure/maintainers.md
=> [Clojure] Bootstrap

languages/fsharp/config.json
=> [F#] Remove "foregone" property from config.json

languages/python/_sidebar.md, languages/python/docs/README.md, languages/python/exercises/README.md, languages/python/reference/README.md
Following this [Ruby PR](https://github.com/exercism/v3/pull/128/), add a sidebar to the Python track with the same folders structure (which was based on the C# folders structure).
=> [Python] Add sidebar information

languages/csharp/config.json
=> [C#] Remove "foregone" property from config.json

languages/elixir/maintainers.md
=> Adds fireproofsocks as maintainer

languages/erlang/README.md, languages/erlang/maintainers.md
Adding myself as a senior maintainer.
=> [erlang] [maintainer] Add NobbZ to `maintainer.md`

languages/common-lisp/README.md, languages/common-lisp/maintainers.md
At present there are no contributing maintainers.
Also check off the checkbox in the track README. I think this task is done for now.
=> [Common Lisp] update maintainers file

languages/common-lisp/README.md, languages/common-lisp/config.json
This should be the minimum needed for an empty track.
=> [Common Lisp] Create initial config.json file

.github/labeler.yml, README.md, languages/java/README.md, languages/java/docs/implementing-a-concept-exercise.md, languages/java/maintainers.md
=> [Java] Bootstrap

languages/java/maintainers.md
@sshine @pdmoore, @mirkoperillo Please double check I got your info correct 😄
=> [Java] add sshine, mirko, pdmoore and msomji as contributing maintainers

languages/common-lisp/config.json
=> [Common Lisp] Fix config.json validity issue.

reference/concepts/arithmetic.md
re: #163
Citation style used: Science of Computer Programming
=> Concept - Arithmetic - citation added

reference/concepts/ascii.md
Add a citation for `reference/concepts/ascii/citations`.
Per #163
=> [reference/concepts] Add quote source

languages/kotlin/README.md, languages/kotlin/config.json
New (and empty) v3 `config.json` for Kotlin track.
=> [Kotlin] Add `config.json` for Kotlin

languages/clojure/maintainers.md
=> [Clojure] Update maintainers.md | User: bemself

languages/common-lisp/README.md
Strike through kick-off task.
As a solo maintainer I don't need to talk with myself about the kick-off of this project.
If more maintainers appear I can do this at that time.
=> [Common Lisp] complete kick-off task

languages/python/maintainers.md
Add myself as a senior maintainer.
=> [python] Add yawpitch as senior maintainer

languages/python/README.md
Updates the readme to reflect the state of Python's Analyzer, Representer, and Test Runner.
=> [python] update README.md

languages/kotlin/maintainers.md
Only those maintainers added who responded [here](https://github.com/exercism/kotlin/issues/406) in the same order.
=> [Kotlin] Add Kotlin track maintainers

.github/labeler.yml, README.md, languages/factor/README.md, languages/factor/docs/implementing-a-concept-exercise.md, languages/factor/maintainers.md
=> [Factor] Bootstrap

languages/go/maintainers.md
Add Michele Caci as new maintainer for the go track of Exercism
=> Add Michele Caci to maintainers.md

languages/java/README.md
=> [Java] Fill out maintainers.md

languages/dart/maintainers.md
PS @exercism/dart, If anyone wants to be added as part of this PR, comment/suggest changes and I'll do it.
=> Add @devkabiir as maintainer for dart track

languages/elm/maintainers.md
Create maintainers.md and add myself to it, as requested on slack.
I haven't added any of the current maintainers, in case they no longer wish to be involved.
=> [Elm] Add Cedd Burge as a maintainer

.github/labeler.yml
Automatically adds CI label to PR's that edit the .github folder.
=> [CI] Automatically add CI label

languages/javascript/docs/README.md
I notice `javascript/docs/README.md` is missing, so I add it.
=> [JavaScript] add README.md

languages/cpp/maintainers.md
=> [C++] Add Rohit Goswami as a maintainer

docs/concept-exercises.md
This file is needed for the experiment but not yes specified firmly enough to be something we should have the V3 Maintainers to use. It'll come back but let's firm up the final spec first, which will take a month or two.
=> Remove reference to exercise specific config.json

languages/go/reference/exercise-concepts/scrabble.md
=> [Go] Concepts of scrabble

docs/concept-exercises.md
Just a grammar correction that looks needed.
=> Grammar Update concept-exercises.md

languages/go/reference/exercise-concepts/hamming.md
Add languages/go/reference/exercise-concepts/hamming.md
First take at capturing hamming concepts for Go.
Attempts to fix #235
=> [Go] Concepts of hamming

languages/cpp/maintainers.md
=> [C++] Add AeroStun as a maintainer

languages/csharp/reference/exercise-concepts/book-store.md
=> [C#] Extract concepts of v2 book-store exercise

languages/cpp/maintainers.md
=> [C++] Add Silvano Cerza as maintaner

languages/cpp/reference/README.md
Initial concepts list, copied and translated from the C# one.
=> [C++] Initial concepts; derived from the C# list

languages/csharp/reference/exercise-concepts/robot-name.md
=> [C#] extract concepts of v2 robot-name exercise

languages/rust/reference/exercise-concepts/decimal.md
Closes #248 
Approached a little different this time now that the core set of concepts start crystallizing. I've taken two reasonably different solutions and extracted applied language components. There's some overlap between some concepts (like `Ordering` and `conditionals`), but I think it's reasonable to touch such concepts in multiple concept-exercises.
=> [Rust] Extract Concepts from v2 exercise decimal

languages/csharp/reference/exercise-concepts/nucleotide-count.md
Closes #260
@robkeim @shaynuhcon For your inspiration, this is my first extraction of concepts.
=> [C#] Extract concepts of v2 nucleotide-count exercise

.github/labeler.yml, README.md, languages/racket/README.md, languages/racket/docs/implementing-a-concept-exercise.md, languages/racket/maintainers.md
=> [Racket] Bootstrap

languages/fsharp/reference/exercise-concepts/bob.md
=> [F#] Extract Concepts from v2 exercise: bob

languages/fsharp/reference/exercise-concepts/meetup.md
=> [F#] Extract Concepts from v2 exercise: meetup

languages/csharp/reference/exercise-concepts/bowling.md
=> [C#] Extract concepts of v2 bowling exercise

languages/java/README.md
=> [Java] kickoff meeting done

languages/ruby/reference/exercise-concepts/nucleotide-count.md
Closes #281 
I used https://github.com/exercism/v3/pull/289 as inspiration for this one
=> [Ruby] Extract concepts of v2 nucleotide-count exercise

languages/go/maintainers.md
Just adding myself to the Go track maintainers list
=> Add DavyJ0nes to list of Go maintainers

languages/c/maintainers.md
To sync with https://github.com/exercism/c/pull/436
=> Add l0nax to maintainers

languages/elixir/reference/README.md
https://github.com/exercism/v3/pull/447 needs merged first so the default argument link is not broken
=> [Elixir] start reference readme

languages/rust/reference/exercise-concepts/paasio.md
Closes #440.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/exercism/v3/441)
=> [Rust] Extract Concepts from v2 exercise: paasio

languages/rust/README.md
I had no part; just lurked
https://exercism-team.slack.com/archives/CC48Y3H1B/p1579683408007400.
=> [Rust] complete kick-off discussion

.github/labeler.yml, README.md, languages/perl5/README.md, languages/perl5/docs/implementing-a-concept-exercise.md, languages/perl5/maintainers.md
=> [Perl5] Add bootstrap

languages/dart/keywords/abstract.md, languages/dart/keywords/class.md, languages/dart/keywords/extends.md
👋 @exercism/dart
I explained  what  the keyword `abstract` was. Let me know how I can improve the PR.
=> [Dart] Explains 'abstract' keyword

docs/maintainers/README.md
Per https://exercism-team.slack.com/archives/CR91YFNG3/p1580766807084200
=> [Docs] change general room to #v3

languages/scala/reference/concept-exercises/scrabble-score.md
=> [Scala] Extract concepts from v2 scrabble-score exercise

languages/scala/reference/exercise-concepts/space-age.md
=> [Scala] Extract concepts from v2 space-age exercise

languages/cpp/_sidebar.md, languages/cpp/docs/README.md, languages/cpp/exercises/README.md, languages/cpp/exercises/_sidebar.md, languages/cpp/exercises/concept/README.md, languages/cpp/exercises/concept/_sidebar.md, languages/cpp/exercises/practice/README.md, languages/cpp/exercises/shared/.docs/README.md, languages/cpp/reference/_sidebar.md
=> [C++] Added essential documentation and folder structure

languages/cpp/reference/exercise-concepts/hamming.md
=> [Cpp] Extract Concepts from v2 exercise: hamming

languages/csharp/reference/exercise-concepts/grade-school.md
=> [C#] Extract concepts from v2 grade-school exercise

languages/java/reference/exercise-concepts/rna-transcription.md
Initial version, need feedback
=> [Java] Extract concepts from v2 rna-transcription exercise

languages/elixir/reference/README.md
Adding in some changes as suggested by @devonestes.
---
A question still remaining as I didn't have a firm answer myself or how as we should deal with them: 
@devonestes wrote:
> Do users see this breakdown of these concepts as "functional"? If so, we should probably remove immutability, recursion and pipelines since they're all found in procedural and OO languages as well.
( [link](https://github.com/exercism/v3/pull/448#discussion_r374300810) )
=> [Elixir] Concept Reference Updates

languages/csharp/reference/exercise-concepts/change.md
=> [C#] Extract concepts from v2 change exercise

languages/elixir/reference/exercise-concepts/scale-generator.md
Another exercise evaluated... I'm not sure if my objections to the exercise instructions should be put into the comments -- they are currently in the `scale-generator.md` file.
For Issue #423
=> [Elixir] Adds concepts and explanation of exercise

languages/elixir/reference/exercise-concepts/rna-transcription.md
My first PR...
My first go at for Issue #421
=> [Elixir] Adds concept list for rna-transcription exercise

languages/csharp/reference/exercise-concepts/two-fer.md
=> [C#] Extract concepts from v2 exercise two-fer

languages/csharp/reference/exercise-concepts/isbn-verifier.md
Closes #397 
Didn't find a lot of concepts here. Let me know if I missed anything.
=> [C#] extract concepts of v2 isbn-verifier exercise

languages/java/README.md, languages/java/config.json
Initial structure for new config.json file for the Java track
=> [Java] add initial config.json file structure

languages/csharp/reference/exercise-concepts/rna-trascriptions.md
Still a work in progress, not ready for review.
Working on #623
=> [C#] Extract Concepts from v2 exercise: rna-transcriptions

languages/csharp/exercises/concept/numbers/.meta/design.md
=> [C#] Update design of numbers exercise

languages/java/reference/exercise-concepts/matrix.md
work in progress, feedback are appreciated
ref to #443
=> [Java] extract concepts from matrix v2 exercise

languages/csharp/reference/exercise-concepts/leap.md
=> [C#] Extract concepts from v2 exercise: leap

.github/workflows/wip.yml
@ErikSchierboom Just for comparison, this would run the wip/action script "natively" and not inside a container.
=> [CI] Add workflow to make prevent work-in-progress PRs from being merged

languages/python/reference/exercise-concepts/reverse-string.md
=> [Python] Extract Concepts from v2 exercise: reverse-string 

languages/python/reference/exercise-concepts/binary-search-tree.md
First concepts for binary-search-tree issue #392
=> [Python] Add Concepts from v2 exercise: binary-search-tree

languages/python/reference/exercise-concepts/allergies.md
First pass concepts for `allergies` to address #460
=>  [Python] Add Concepts from v2 exercise: allergies

languages/python/reference/exercise-concepts/leap.md
First pass list of concepts to address #459
=> [Python] Add Concepts from v2 exercise: leap

languages/python/reference/exercise-concepts/phone-number.md
https://github.com/exercism/v3/issues/419
=> [Python] Add Concepts for v2 exercise: phone-number

languages/python/reference/exercise-concepts/hamming.md
Iterables/iterators, gen expressions, list comprehensions will all need a lot more detail once they exist as concepts, but this PR focuses on the key points for this exercise.
https://github.com/exercism/v3/issues/417
=> [Python] Add Concepts for v2 exercise: hamming

languages/python/reference/exercise-concepts/clock.md
:warning: First draft with some ideas. Don't bother reviewing.
=> [DRAFT] [Python] Add Concepts for v2 exercise: clock

languages/csharp/maintainers.md
Add myself to the maintainers.md file.
=> Add EarthlingRich to maintainers.md

languages/python/docs/implementing-a-concept-exercise.md
Already applied some changes as per review on PR #223 (erroneously closed).
=> [WIP] [Python] Concept implementation instructions

languages/clojure/exercises/concept/list/.meta/design.md
@porkostomus I like your thoughts, that's really nice, thus opening this PR to add the design doc and meantime discuss the details of the design of list, set and vector
yes cannot agree more, this should be the focus of concept list, I left a question in the instructions.md but never touch it in the exercise...
> I feel like we should really nail down the idea of the list representing a function call, which leads naturally into quoting and evaluation (the latter of which will be covered by another exercise). 
also agree with you, we can do the full test suite for the exercise on sets. as for lists, how about we just mention like create/add/count?
> Conversely, I'm feeling that the bit about testing membership might be better saved for the exercise on sets
=> [Clojure]: Init design.md for concept List

languages/csharp/exercises/concept/numbers/.docs/hints.md, languages/csharp/exercises/concept/numbers/.docs/instructions.md, languages/csharp/exercises/concept/numbers/.docs/introduction.md, languages/csharp/exercises/concept/numbers/.meta/Example.cs
I have some feedback on the numbers exercise:
- The word singed should be introduced in a more advanced exercise. The exercises about unsigned integers will be a good place.
- The 0% success rate seems unnecessary. A success rate should not apply when there is no production. This also leads to more clear code.
- Some text and information improvements.
=> [C#] Feedback on numbers exercise

languages/go/reference/exercise-concepts/parallel-letter-frequency.md
=> [Go] add concepts for v2's parallel letter frequency

languages/csharp/maintainers.md
Hi,
Update the maintainers list as per the request made in #maintaining-csharp channel.
~Senal
=> [C#] Update maintainers list

languages/common-lisp/reference/exercise-concepts/roman-numerals.md
=> [Common Lisp] add proposed concepts from roman-numeral exercise.

languages/cpp/reference/exercise-concepts/two-fer.md
=> [C++] Extract concepts from v2 exercise: two-fer

languages/csharp/reference/exercise-concepts/book-store.md, languages/csharp/reference/exercise-concepts/isbn-verifier.md, languages/csharp/reference/exercise-concepts/leap.md, languages/csharp/reference/exercise-concepts/protein-translation.md, languages/csharp/reference/exercise-concepts/rna-trascriptions.md, languages/csharp/reference/exercise-concepts/robot-name.md, languages/csharp/reference/exercise-concepts/two-fer.md
Just some normalization of the formats used
=> [C#] Normalize format of exercise-concepts

languages/rust/reference/exercise-concepts/luhn.md
=> [Rust] extract concepts for luhn

languages/rust/reference/exercise-concepts/leap.md
=> [Rust] extract conceps from leap

languages/csharp/reference/exercise-concepts/high-scores.md
=> [C#] Extract concepts from v2 exercise: high-scores (new)

languages/python/README.md, languages/python/config.json
=> [Python] add config.json skeleton

languages/csharp/exercises/concept/strings/.docs/introduction.md
Copy Ruby introduction to the C# repo.
=> [C#] Update introduction.md

languages/java/reference/exercise-concepts/leap.md
First pass at this. Appreciate any feedback.
=> [Java] Extract concepts from v2 exercise: leap

languages/common-lisp/reference/exercise-concepts/word-count.md
Closes #496. Would love some feedback!
=> [Common Lisp] Extract Concepts from Word Count

languages/common-lisp/reference/exercise-concepts/rna-transcription.md
Closes #495, but needs some review and I would appreciate feedback from the other CL track maintainers!
=> [Common Lisp] Extract CL Concepts from RNA Transcription

languages/cpp/reference/exercise-concepts/trinary.md
=> [C++] Extract concepts from v2 exercise: trinary

languages/rust/reference/README.md
I added this to delineate what Exercism Concepts intend per discussions in slack and #706
I also fixed a few typos.
=> [Rust] expand and caveat concepts reference

languages/common-lisp/reference/exercise-concepts/anagram.md
=> [Common Lisp] add proposed concepts from anagram exercise.

languages/fsharp/.gitignore, languages/fsharp/config.json, languages/fsharp/exercises/concept/README.md, languages/fsharp/exercises/concept/strings/.docs/after.md, languages/fsharp/exercises/concept/strings/.docs/hints.md, languages/fsharp/exercises/concept/strings/.docs/instructions.md, languages/fsharp/exercises/concept/strings/.docs/introduction.md, languages/fsharp/exercises/concept/strings/.meta/Example.fs, languages/fsharp/exercises/concept/strings/.meta/config.json, languages/fsharp/exercises/concept/strings/.meta/design.md, languages/fsharp/exercises/concept/strings/Strings.fs, languages/fsharp/exercises/concept/strings/Strings.fsproj, languages/fsharp/exercises/concept/strings/StringsTest.fs, languages/fsharp/reference/README.md, reference/types/string.md
=> [F#] Add strings Concept Exercise

languages/go/exercises/concept/basic-slices/.docs/after.md, languages/go/exercises/concept/basic-slices/.docs/hints.md, languages/go/exercises/concept/basic-slices/.docs/instructions.md, languages/go/exercises/concept/basic-slices/.docs/introduction.md, languages/go/exercises/concept/basic-slices/.meta/config.json, languages/go/exercises/concept/basic-slices/.meta/design.md, languages/go/exercises/concept/basic-slices/.meta/example.go, languages/go/exercises/concept/basic-slices/basic_slices.go, languages/go/exercises/concept/basic-slices/basic_slices_test.go, languages/go/exercises/concept/basic-slices/go.mod
Closes #530 
Intended concepts to teach:
**working with slices**
- instantiate (len, cap)
- append
- set value
- read value
- remove value
- taking length
- subslices
- expanding slices
Here you can find the [Implementation Guide](https://github.com/exercism/v3/blob/master/languages/go/docs/implementing-a-concept-exercise.md).
=> [Go] Concept Exercise: basic-slices

languages/fsharp/docs/README.md, languages/fsharp/docs/string_concatenation.md
=> [F#] Add reference document for string concatenation

languages/cpp/reference/README.md
Added fixed width integer types and expand IO concepts
=> Extend cxx concepts

languages/cpp/reference/exercise-concepts/raindrops.md
I wonder if there should be a separate Concept for streams in STL? Please let me know what you think about that.
=> [C++] Add concepts for v2's raindrops

languages/Elm/reference/exercise-concepts/raindrops.md
=> [Elm] Extract Concepts from v2 exercise: raindrops

languages/Elm/reference/exercise-concepts/bob.md
=> [Elm] Extract Concepts from v2 exercise: bob

languages/python/reference/README.md
I'll do asap a review of this concepts for duplicates, typos etc.
=> [WIP] [Python] Extracted concept unification

languages/cpp/reference/exercise-concepts/grains.md
=> [C++] Extract Concepts from v2 exercise: grains

languages/julia/reference/exercise-concepts/rna-transcription.md
=> [Julia] Extract concepts from v2 exercise: rna-transcription

languages/rust/exercises/concept/numbers/.docs/after.md, languages/rust/exercises/concept/numbers/.docs/hints.md, languages/rust/exercises/concept/numbers/.docs/instructions.md, languages/rust/exercises/concept/numbers/.docs/introduction.md, languages/rust/exercises/concept/numbers/.meta/config.json, languages/rust/exercises/concept/numbers/.meta/design.md, languages/rust/exercises/concept/numbers/.meta/example.rs, languages/rust/exercises/concept/numbers/Cargo.toml, languages/rust/exercises/concept/numbers/src/lib.rs, languages/rust/exercises/concept/numbers/tests/numbers.rs
As the title says. I welcome some feedback about the use of casting in this exercise. Is this a sensible approach when considering Rust's rigid type-checker or should it be simpler?
=> [Rust] Port concept exercise numbers from C#

languages/kotlin/.gitignore, languages/kotlin/settings.gradle.kts
Creating composite build for Kotlin exercises.
Just import `languages/kotlin` folder to IDE as a Gradle project.
=> [Kotlin] Create composite root build for exercises

languages/ruby/exercises/concept/README.md
I was comparing the C# track folder structure with the Ruby track and realised that after https://github.com/exercism/v3/pull/738 I didn't create the README file on the `concept` folder.
=> Add concept README.md file

languages/cpp/reference/exercise-concepts/pangram.md
=> [C++] Extract Concepts from v2 exercise: pangram

languages/haskell/reference/implementing-a-concept-exercise.md
This PR consists of three separate commits.
See the commit history.
This closes #55.
*Ideally this PR should be merge-committed to preserve the separation of commits as well as their common relation to this PR, but because merge commits are disabled in this repository, the next-best alternative is a rebase, since each commit's header is prefixed with `[Haskell]` and does something for itself.*
=> [Haskell] Revise contribution guide

languages/elixir/reference/exercise-concepts/robot-simulator.md
Close #299.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/exercism/v3/861)
=> [Elixir] Extract Concepts from v2 exercise: robot-simulator

languages/elixir/reference/README.md, languages/elixir/reference/exercise-concepts/word-count.md
I'm open to including other approaches here. I considered a `String.split/3` based approach, but I don't think it really changes the concepts as it will eventually use Regex to deal with UTF-8 characters as well.
Closes #302
=> [Elixir] word-count concept extraction

reference/concepts/README.md, reference/concepts/actor_model.md, reference/concepts/eager_evaluation.md, reference/concepts/lazy_evaluation.md, reference/concepts/utf16.md, reference/concepts/utf32.md, reference/concepts/utf8.md
@ErikSchierboom I'm not sure who to tag this one for reviewers as this is the first new reference I have submitted.
---
This expands upon the UTF7 and UTF8 references
Also adds lazy and eager computation
Also adds actor model
=> [Reference] Adding to general reference

languages/cpp/reference/exercise-concepts/sieve.md
Closes #600 
The current tests for this exercise expect a `prime` function with an `int` argument and that returns a `vector<int>`, I think this could be changed to use `unsigned int` since prime numbers can only be positive. Just a personal consideration.
=> [C++] Extract concepts from v2 exercise: sieve

languages/cpp/reference/README.md
As discussed on #787 I added some two new concepts, `Vector` was already present.
=> [C++] Added two new concepts

languages/cpp/reference/exercise-concepts/anagram.md
=> [C++] Extract Concepts from v2 exercise: anagram

languages/common-lisp/reference/implementing-a-concept-exercise.md
=> [Common Lisp] Update implementation guidelines to exclude ASDF

languages/fsharp/config.json, languages/fsharp/exercises/concept/README.md, languages/fsharp/exercises/concept/dates/.docs/after.md, languages/fsharp/exercises/concept/dates/.docs/hints.md, languages/fsharp/exercises/concept/dates/.docs/instructions.md, languages/fsharp/exercises/concept/dates/.docs/introduction.md, languages/fsharp/exercises/concept/dates/.meta/Example.fs, languages/fsharp/exercises/concept/dates/.meta/config.json, languages/fsharp/exercises/concept/dates/.meta/design.md, languages/fsharp/exercises/concept/dates/Dates.fs, languages/fsharp/exercises/concept/dates/Dates.fsproj, languages/fsharp/exercises/concept/dates/DatesTests.fs, languages/fsharp/reference/README.md, reference/types/datetime.md
=> [F#] Implement new Concept exercise dates

languages/cpp/reference/exercise-concepts/isogram.md
=> [C++] Extract Concepts from v2 exercise: isogram

languages/emacs-lisp/reference/exercise-concepts/rna-transcription.md
=> [Emacs Lisp] First draft of rna concepts

docs/maintainers/faqs.md, reference/concepts/actor_model.md, reference/concepts/ascii.md, reference/concepts/default_arguments.md, reference/concepts/eager_evaluation.md, reference/concepts/lazy_evaluation.md, reference/concepts/macros.md, reference/concepts/metaprogramming.md, reference/concepts/multiple-dispatch.md, reference/concepts/prototype_based-programming.md, reference/concepts/signedness.md, reference/concepts/undefined.md, reference/concepts/utf16.md, reference/concepts/utf32.md, reference/concepts/utf8.md, reference/types/signed.md
Closes https://github.com/exercism/v3/issues/163
I'm not sure if this should go anywhere else as well?
=> Add FAQ about Citations

languages/elixir/README.md, languages/elixir/exercises/concept/README.md, languages/elixir/reference/implementing-a-concept-exercise.md
A first draft inspired by the guides created by the csharp, javascript and julia tracks.
=> [Elixir] Implementing a Concept Exercise Guide

languages/elixir/reference/README.md, languages/elixir/reference/exercise-concepts/secret-handshake.md
I tried to keep it to the core concepts necessary or very likely to be encountered when completing the exercise instead of every concept that may be encountered. Is there any guidance on how to handle a range of possible concepts?
Closes #303
=> elixir concepts extraction for secret-handshake

languages/javascript/reference/exercise-concepts/beer-song.md
=> [JavaScript] Create beer-song.md

languages/javascript/reference/exercise-concepts/bob.md
=> [Javascript] - Extract concepts of v2 bob exercise

languages/c/reference/exercise-concepts/two-fer.md
=> [C] Extract concepts of v2 two-fer exercise

languages/rust/reference/exercise-concepts/macros.md
Closes https://github.com/exercism/v3/issues/245
=> [Rust] Extract concepts from v2 exercise: macros

.github/labeler.yml, README.md, languages/r/README.md, languages/r/maintainers.md, languages/r/reference/implementing-a-concept-exercise.md
=> [R] Bootstrap track

languages/csharp/reference/examples/new-concept-exercise-arrays.md
This will make it easier to copy/paste/modify it for other new exercise issues.
=> [C#] Simplify new exercise issue

languages/fsharp/exercises/concept/lists/.docs/introduction.md
=> [F#] Add code syntax samples to lists exercise

languages/fsharp/exercises/concept/strings/.docs/introduction.md
=> [F#] Add code syntax samples to strings exercise

languages/fsharp/exercises/concept/numbers/.docs/introduction.md
=> [F#] Add code syntax samples to numbers exercise

languages/csharp/exercises/concept/dates/DatesTests.cs, languages/csharp/exercises/concept/enums-advanced/EnumsAdvancedTests.cs, languages/csharp/exercises/concept/enums/EnumsTests.cs, languages/csharp/exercises/concept/numbers-floating-point/NumbersFloatingPointTests.cs, languages/csharp/exercises/concept/numbers/NumbersTests.cs, languages/csharp/exercises/concept/strings/StringsTests.cs
=> [C#] Add skip attribute

languages/cpp/exercises/concept/README.md, languages/cpp/exercises/concept/_sidebar.md, languages/cpp/exercises/concept/strings/.docs/after.md, languages/cpp/exercises/concept/strings/.docs/hints.md, languages/cpp/exercises/concept/strings/.docs/instructions.md, languages/cpp/exercises/concept/strings/.docs/introduction.md, languages/cpp/exercises/concept/strings/.meta/config.json, languages/cpp/exercises/concept/strings/.meta/design.md, languages/cpp/exercises/concept/strings/.meta/example.cpp, languages/cpp/exercises/concept/strings/.meta/example.h, languages/cpp/exercises/concept/strings/CMakeLists.txt, languages/cpp/exercises/concept/strings/strings.cpp, languages/cpp/exercises/concept/strings/strings.h, languages/cpp/exercises/concept/strings/strings_test.cpp, languages/cpp/exercises/concept/strings/test/catch.hpp, languages/cpp/exercises/concept/strings/test/tests-main.cpp
Closes #1010 
I followed the [C# strings exercise][csharp-strings] as inspiration.
[csharp-strings]: https://github.com/exercism/v3/tree/master/languages/csharp/exercises/concept/strings
=> [C++] Add concept exercise strings

languages/csharp/exercises/concept/numbers-floating-point/.docs/introduction.md
=> [C#] Add code syntax samples to numbers-floating-point exercise

languages/csharp/exercises/concept/enums/.docs/after.md, languages/csharp/exercises/concept/enums/.docs/introduction.md
=> [C#] Add code syntax samples to enums exercise

languages/csharp/exercises/concept/numbers/.docs/introduction.md
=> [C#] Add code syntax samples to numbers exercise

languages/csharp/config.json, languages/csharp/exercises/concept/enums-advanced/.docs/after.md, languages/csharp/exercises/concept/enums-advanced/.docs/introduction.md, languages/csharp/exercises/concept/enums-advanced/.meta/design.md
=> [C#] Add code syntax samples to enums-advanced exercise

languages/csharp/exercises/concept/strings/.docs/introduction.md
=> [C#] Add code syntax samples to strings exercise

languages/csharp/exercises/concept/properties/.meta/config.json
Some invisible nastiness had found its way into the string.
=> Corrected invalid Json token

languages/csharp/exercises/concept/basics/.docs/instructions.md, languages/csharp/exercises/concept/basics/.meta/design.md, languages/csharp/exercises/concept/dates/.docs/instructions.md, languages/csharp/exercises/concept/enums-advanced/.docs/instructions.md, languages/csharp/exercises/concept/enums/.docs/instructions.md, languages/csharp/exercises/concept/numbers-floating-point/.docs/instructions.md, languages/csharp/exercises/concept/numbers/.docs/instructions.md, languages/csharp/exercises/concept/strings/.docs/instructions.md
=> [C#] Add parentheses to method names

languages/fsharp/exercises/concept/booleans/BooleansTests.fs, languages/fsharp/exercises/concept/dates/DatesTests.fs, languages/fsharp/exercises/concept/discriminated-unions/DiscriminatedUnionsTests.fs, languages/fsharp/exercises/concept/lists/ListsTests.fs, languages/fsharp/exercises/concept/numbers-floating-point/NumbersFloatingPointTests.fs, languages/fsharp/exercises/concept/numbers/NumbersTests.fs, languages/fsharp/exercises/concept/recursion/RecursionTests.fs, languages/fsharp/exercises/concept/strings/StringsTests.fs
Improving skip string per #1047
Ran: `grep -ril "Remove to run test" . | xargs sed -i "s/Remove to run test/Remove this Skip property to run this test/"`
=> [F#] Improve Skip string #1047

languages/csharp/exercises/concept/basics/BasicsTests.cs, languages/csharp/exercises/concept/dates/DatesTests.cs, languages/csharp/exercises/concept/enums-advanced/EnumsAdvancedTests.cs, languages/csharp/exercises/concept/enums/EnumsTests.cs, languages/csharp/exercises/concept/numbers-floating-point/NumbersFloatingPointTests.cs, languages/csharp/exercises/concept/numbers/NumbersTests.cs, languages/csharp/exercises/concept/properties/PropertiesTests.cs, languages/csharp/exercises/concept/strings/StringsTests.cs
Improving skip string per #1047 
Ran: `grep -ril "Remove to run test" . | xargs sed  -i "s/Remove to run test/Remove this Skip property to run this test/"`
=> [C#] Improve Skip string #1047

languages/x86-64-assembly/reference/exercise-concepts/two-fer.md
=> [x86-64-assembly] Extract Concepts from v2 exercise: two-fer

languages/cpp/config.json
=> [C++] Add track config.json

.github/bin/concept-checks/concept-checks.jl, .github/workflows/concept-ci.yml, docs/maintainers/continuous-integration.md
Pinging @SaschaMann to sanity check things!
=> Enable selective checking of concepts.csv

languages/c/README.md, languages/c/reference/README.md
A PR for the concepts list as so far discussed on #201 . I have added the suggestions made to date on that issue. Those suggestions have not been added in any particular order, the order is one area that can most likely benefit from continued discussions.
My aim in moving to a PR is to make it easier to make changes that can be recorded as part of the repo under change control and so as to move toward having the first draft of the document reach a stage of completeness. Discussion can continue here (as well as in future PRs) as needed 😃
=> Start C concepts list

languages/python/reference/README.md
Feel free to prune if needed.   Added "tracking table" with Concept Name, Issue Link and PR Link columns to the reference README.md.
=> [Python] Added tracking table for open issues & PRs related to concept exercises

languages/javascript/exercises/concept/booleans/.docs/instructions.md, languages/javascript/exercises/concept/booleans/booleans.js, languages/javascript/exercises/concept/booleans/booleans.spec.js, languages/javascript/exercises/concept/booleans/example.js
Updated the instructions based on the F# track. Seems more clear.
=> Update javascript booleans concept instructions

languages/cpp/reference/implementing-a-concept-exercise.md
Updated `implementing-a-concept-exercise.md` manual for `cpp` track based on `docs/maintainers/generic-how-to-implement-a-concept-exercise.md`
=> [C++] Update implementing-a-concept-exercise.md

languages/rust/maintainers.md
After discussing with @efx and @coriolinus I realized I was being very silly by not formally adding myself as a maintainer. Here's to version control.
=> &self -> RustMaintainer

languages/common-lisp/reference/README.md, languages/common-lisp/reference/concepts.csv
So we can actually teach printing to standard output somewhere
=> [Common Lisp] Add IO concepts

languages/ruby/config.json, languages/ruby/exercises/concept/README.md, languages/ruby/exercises/concept/basics/.docs/after.md, languages/ruby/exercises/concept/basics/.docs/hints.md, languages/ruby/exercises/concept/basics/.docs/instructions.md, languages/ruby/exercises/concept/basics/.docs/introduction.md, languages/ruby/exercises/concept/basics/.meta/config.json, languages/ruby/exercises/concept/basics/.meta/design.md, languages/ruby/exercises/concept/basics/.meta/example.rb, languages/ruby/exercises/concept/basics/lasagna.rb, languages/ruby/exercises/concept/basics/lasagna_test.rb
This is documented in [this video](https://www.youtube.com/watch?v=esQhPx2U1uk).
@pvcarrera has offered to try and get it finished :)
=> Add Ruby/Basics exercise

languages/javascript/reference/exercise-concepts/pangram.md
=> [Javascript] - Extract concepts of v2 pangram exercise

languages/csharp/config.json
The concept naming has been updated lately.
=> [C#] Use integral-numbers concept

languages/c/README.md, languages/c/reference/_sidebar.md, languages/c/reference/implementing-a-concept-exercise.md
#1027 reborn, due to my inability to recover my local repo after the great master force push of 'ought-twenty.
=> [C] Add implementing concept exercise reference

languages/cpp/exercises/concept/strings/.meta/config.json
=> [C++] Updated Concept exercises config.json format

languages/common-lisp/exercises/concept/basics/.meta/config.json
=> [Common Lisp] Update .meta/config.json files

languages/ruby/exercises/concept/basics/.meta/config.json, languages/ruby/exercises/concept/strings/.meta/config.json
ref: #1190
/cc @ihid @pvcarrera
=> [Ruby] exercise author credit for basic and string

languages/elixir/reference/exercise-concepts/bracket-push.md
My 2nd PR (hope I'm doing this correctly)...
PR for Issue #422
=> [Elixir] Adds concepts to bracket-push exercise

languages/javascript/exercises/concept/booleans/.meta/config.json, languages/javascript/exercises/concept/numbers/.meta/config.json, languages/javascript/exercises/concept/promises/.meta/config.json, languages/javascript/exercises/concept/strings/.meta/config.json, languages/javascript/exercises/practice/string-iterables/.meta/config.json
=> [JavaScript] Update all exercise .meta/config.json

reference/concepts/assignment.md, reference/concepts/comments.md, reference/concepts/constants.md, reference/concepts/expressions.md, reference/types/boolean.md, reference/types/floating_point_number.md, reference/types/function.md, reference/types/integer.md, reference/types/number.md, reference/types/string.md, reference/types/symbol.md
I've tried to add all the missing exercise references.
=> [Docs] Add missing implementation references

languages/ruby/reference/exercise-concepts/resistor-color-duo.md
=> [Ruby] Add resistor-color-duo concept extraction

languages/javascript/config.json
=> [JavaScript] New naming convention for concepts in config.json

languages/rust/config.json
Aiming to nab these small tasks in free moments here and there.
=> [Rust] migrate config.json

.editorconfig, .prettierignore, bin/format.cmd, bin/format.sh
=> [Docs] Support auto-formatting

languages/elixir/config.json, languages/elixir/exercises/concept/README.md, languages/elixir/exercises/concept/basics/.docs/after.md, languages/elixir/exercises/concept/basics/.docs/hints.md, languages/elixir/exercises/concept/basics/.docs/instructions.md, languages/elixir/exercises/concept/basics/.docs/introduction.md, languages/elixir/exercises/concept/basics/.formatter.exs, languages/elixir/exercises/concept/basics/.gitignore, languages/elixir/exercises/concept/basics/.meta/config.json, languages/elixir/exercises/concept/basics/.meta/design.md, languages/elixir/exercises/concept/basics/.meta/example.ex, languages/elixir/exercises/concept/basics/lib/lasagna.ex, languages/elixir/exercises/concept/basics/mix.exs, languages/elixir/exercises/concept/basics/test/lasagna_test.exs, languages/elixir/exercises/concept/basics/test/test_helper.exs, languages/elixir/reference/README.md, reference/concepts/assignment.md
A port of the C# basics concept exercise for Elixir.
Adds the following:
```text
.
├── .docs
│   ├── after.md
│   ├── hints.md
│   ├── instructions.md
│   └── introduction.md
├── .formatter.exs
├── .gitignore
├── lib
│   └── lasagna.ex
├── .meta
│   ├── config.json
│   ├── design.md
│   └── example.ex
├── mix.exs
└── test
├── lasagna_test.exs
└── test_helper.exs
```
=> [Elixir] Concept exercise: basics

languages/purescript/reference/exercise-concepts/hello-world.md
=> [PureScript] Extract concepts of v2 hello-world exercise

.github/workflows/verify-formatting.yml, .github/workflows/verify-markdown-formatting.yml, docs/maintainers/continuous-integration.md
Depends on #1252 and #1253 being merged.
=> [CI] Check style

languages/purescript/exercises/concept/booleans/.docs/instructions.md
To be more consistent with other languages.
=> [PureScript] Put expected outputs on new line

languages/javascript/exercises/concept/numbers/example.js, languages/javascript/exercises/concept/numbers/numbers.js
=> [JavaScript] number: fix typo

.github/ISSUE_TEMPLATE/implement-concept-exercise.md
I noticed this on most new concept exercise so figured we should add it
to the template.
=> [Docs] add getting started section to concept exercise template

languages/elixir/exercises/concept/booleans/.docs/after.md, languages/elixir/exercises/concept/booleans/.docs/hints.md, languages/elixir/exercises/concept/booleans/.docs/instructions.md, languages/elixir/exercises/concept/booleans/.docs/introduction.md, languages/elixir/exercises/concept/booleans/.meta/config.json, languages/elixir/exercises/concept/booleans/.meta/design.md, languages/elixir/exercises/concept/booleans/.meta/example.ex, languages/elixir/exercises/concept/booleans/lib/rules.ex, languages/elixir/exercises/concept/booleans/mix.exs, languages/elixir/exercises/concept/booleans/test/rules_test.exs
@Cohen-Carlisle had some really good insights into the first merged concept exercise.  I have made the obvious changes, and submit them here.
There are some discussion questions which he through we should more fully discuss which he may add to this discussion.
---
- `is_x` to `x_variable`
- logical variable name change
- terminology changes
- tense changes
- terminology changes
- tense changes
- `is_x` to `x_variable`
- typo fixes
- logical variable name change
- @Cohen-Carlisle added as contributor
- is_ prefix added to out of scope
- parameter name changes to match instructions
- stubs included
- parameter name changes to match instructions
- terminology changes to match instructions
=> [Elixir] Improve Concept Exercise: booleans

.github/workflows/format-code.yml
Add support for formatting code using a comment with `/format` in it.
Closes #1259
=> [CI] Add workflow to format code

.github/workflows/verify-markdown-formatting.yml
Only check the files within a PR when checking the Markdown of a PR
=> [CI] Only check formatting of added or modified markdown files in PR

languages/python/bin/README.md, languages/python/bin/make-concept-exercise
Adds a simple CLI utility to build out the initial skeleton of a new concept exercise. Hopefully this reduces a little of the cognitive overhead of getting going.
=> [Python] Adds make-concept-exercise utility

languages/julia/exercises/concept/functions-introduction/.docs/introduction.md
Fix a typo, give a demo of invoking a function, use the normal word for type inference.
=> [Julia] Update introduction.md

languages/elixir/reference/exercise-concepts/bank-account.md
=> [Elixir] Extract Concepts from v2 exercise: bank-account

languages/rust/reference/exercise-concepts/robot-simulator.md
=> [Rust] Extract Concepts from v2 exercise: robot-simulator

languages/rust/README.md
=> [Rust] indicate progress in readme

docs/maintainers/writing-a-concept-exercise-github-issue.md
=> [Docs] Update writing-a-concept-exercise-github-issue.md

.github/labeler.yml, docs/maintainers/repository-structure.md
=> [Docs] Update labels

languages/README.md, languages/_sidebar.md, languages/emacs-lisp/README.md, languages/emacs-lisp/_sidebar.md, languages/emacs-lisp/config.json, languages/emacs-lisp/docs/README.md, languages/emacs-lisp/exercises/README.md, languages/emacs-lisp/exercises/concept/README.md, languages/emacs-lisp/exercises/practice/README.md, languages/emacs-lisp/maintainers.md, languages/emacs-lisp/reference/README.md, languages/emacs-lisp/reference/implementing-a-concept-exercise.md, languages/emacs-lisp/reference/progression.md
- added a working Concepts list and mermaid chart
- added a `_sidebar.md` and created the relevant docs
- added myself as a maintainer
- updated track progress on the main `README.md`
- added `config.json`
=> [Emacs Lisp] Emacs Lisp concepts

bin/format.cmd, bin/format.sh, docs/concept-exercises.md, docs/maintainers/style-guide.md
=> [Docs] Describe how auto formatting works

languages/python/config.json
Fixes exercise naming per the updated ruled. Closes #1134
=> [Python] Update exercise naming

reference/concepts/assignment.md
Appears that this file became un-pretty. Perhaps I was to blame.
This PR attempts to fix that problem.
=> Running prettier to correct assignment.md file.

languages/common-lisp/bin/generate-scaffolding/README.md
=> [Common Lisp] Fix trailing space in markdown

languages/elixir/exercises/concept/booleans/.docs/after.md, languages/elixir/exercises/concept/booleans/.docs/instructions.md, languages/elixir/exercises/concept/booleans/.docs/introduction.md
@Cohen-Carlisle or @neenjaw -- I noticed a few typos in there when I was looking at the booleans exercise as a reference.  Hope you don't mind the suggested fixes!
=> [Elixir] Concept exercise revision: booleans - typos in copy

languages/javascript/exercises/concept/strings/.docs/hints.md, languages/javascript/exercises/concept/strings/.docs/instructions.md, languages/javascript/exercises/concept/strings/.meta/config.json, languages/javascript/exercises/concept/strings/example.js, languages/javascript/exercises/concept/strings/strings.js, languages/javascript/exercises/concept/strings/strings.spec.js
I removed the reverse task because it relies on a few more advanced features of `array` and this exercise would be prior to `array`. See more detail -> #1298 
We'll introduce `String#trim` instead, so I changed the story accordingly.
I'll add `after.md` in another Issue.
=> [JavaScript] Improve Concept Exercise: strings

languages/javascript/exercises/concept/arrays/.meta/config.json, languages/javascript/exercises/concept/booleans/.meta/config.json
Thank you @peterchu999 and @rishiosaur for these improvements :heart:
=> Add missing contributors to some javascript exercises

languages/common-lisp/bin/generate-scaffolding/generate-scaffolding.lisp, languages/common-lisp/bin/generate-scaffolding/template/<SLUG>.lisp, languages/common-lisp/bin/generate-scaffolding/template/SLUG-test.lisp, languages/common-lisp/bin/generate-scaffolding/template/SLUG.lisp
Whoops, that was a bit of a train-wreck. Should be better now!
=> [Common Lisp] Removed illegial Windows paths

languages/csharp/exercises/concept/basics/.docs/after.md, languages/csharp/exercises/concept/basics/.docs/introduction.md, languages/csharp/exercises/concept/basics/.meta/Example.cs, languages/csharp/exercises/concept/basics/Basics.cs
Simplify things by removing the class' access modifier.
=> [C#][Basics] Remove unneeded class access modifier

.github/workflows/verify-code-formatting.yml
If the prettier config changes, the checks should be rerun.
=> [CI] Trigger prettier workflows on config change

.github/workflows/verify-code-formatting.yml, languages/julia/.prettierrc, languages/julia/config.json, languages/julia/exercises/concept/functions-introduction/.meta/config.json, languages/julia/exercises/concept/multiple-dispatch/.meta/config.json
#1367 introduced a bug where a CI check enforced incorrect indentation levels for the Julia directory.
=> [CI][Julia] Fix incorrect indentation enforced by prettier

languages/clojure/exercises/concept/lists/.docs/introduction.md, reference/stories/basics.lasagna.md, reference/stories/booleans.pac-man.md, reference/stories/lists.language-list.md, reference/stories/maps.high-score-board.md
I'm adding story reference documents used by merges exercises in the elixir track.
My hope is that people can then use these stories and re-interpret them to facilitate their concept needs.
I have tried to include references to implementations that I am aware of for each story.
=> [Reference] Add concept stories

languages/javascript/exercises/concept/arrays/.meta/config.json, languages/javascript/exercises/concept/booleans/.meta/config.json
See https://github.com/exercism/v3/pull/1411
=> [JavaScript] Remove contributors when also author

reference/stories/arrays.garden-bird-count.md, reference/stories/classes.remote-control-car.md, reference/stories/datetimes.appointment-scheduler.md, reference/stories/enums.log-line-parser.md, reference/stories/flag-enums.website-account-permissions.md, reference/stories/floating-point-numbers.savings-account.md, reference/stories/nullability.name-badges.md, reference/stories/numbers.car-production-line.md, reference/stories/pattern-matching.number-guessing-game.md, reference/stories/properties.weighing-machine.md, reference/stories/recursion.pizza-delivery.md, reference/stories/strings.log-line-parser.md, reference/stories/sum-types.valentines-day.md
Please rebase and merge (no squashing) when merging.
=> [Reference] Add more stories

reference/stories/_sidebar.md, reference/stories/shopping-cart.md
This PR copies shopping cart exercise over from the research repository. I think this exercise is complex enough to teach a bunch of things 😄 But probably the main is dealing with the state of the cart
=> [Docs] Add story: shopping cart

languages/javascript/exercises/shared/.docs/cli.md
fixes unecessary newlines and uses consistent syntax highlighting.
=> [JavaScript] Format shared/cli.md

languages/c/maintainers.md
@wolf99 on slack told me that this is a good first thing to do so here it is.
=> [C] Adding my name to the maintainers list

languages/rust/exercises/concept/entry-api/.docs/after.md, languages/rust/exercises/concept/entry-api/.docs/hints.md, languages/rust/exercises/concept/entry-api/.meta/example.rs, languages/rust/exercises/concept/entry-api/tests/entry_api.rs
This PR addresses some additional feedback on the Entry API concept exercise vis a vis #1459
=> [Rust] Additional PR feedback for Entry API Concept Exercise

languages/c/reference/exercise-concepts/square-root.md
=> [C] Extract concepts of v2 square-root exercise

languages/go/exercises/concept/basics/.docs/after.md, languages/go/exercises/concept/basics/.docs/hints.md, languages/go/exercises/concept/basics/.docs/instructions.md, languages/go/exercises/concept/basics/.docs/introduction.md, languages/go/exercises/concept/basics/.meta/config.json, languages/go/exercises/concept/basics/.meta/design.md, languages/go/exercises/concept/basics/.meta/example.go, languages/go/exercises/concept/basics/basics.go
Transferred from C#.
TODO: Tests need to be written.
=> [Go]: New Concept Exercise: basics

languages/elixir/README.md, languages/elixir/config.json, languages/elixir/exercises/concept/README.md, languages/elixir/exercises/concept/tuples/.docs/after.md, languages/elixir/exercises/concept/tuples/.docs/hints.md, languages/elixir/exercises/concept/tuples/.docs/instructions.md, languages/elixir/exercises/concept/tuples/.docs/introduction.md, languages/elixir/exercises/concept/tuples/.formatter.exs, languages/elixir/exercises/concept/tuples/.gitignore, languages/elixir/exercises/concept/tuples/.meta/config.json, languages/elixir/exercises/concept/tuples/.meta/design.md, languages/elixir/exercises/concept/tuples/.meta/example.ex, languages/elixir/exercises/concept/tuples/lib/kitchen_calculator.ex, languages/elixir/exercises/concept/tuples/mix.exs, languages/elixir/exercises/concept/tuples/test/kitchen_calculator_test.exs, languages/elixir/exercises/concept/tuples/test/test_helper.exs, reference/stories/tuples.kitchen-calculator.md, reference/types/tuple.md
Files included:
.docs/introduction.md
- an introduction to tuples, basic pattern matching, and pattern matching on functions
.meta/design.md
- an unfinished design document describing the goals of the exercise
.meta/example.ex
- an example solution to display the intended goal of the exercise
=> [Elixir] New concept exercise: tuples

languages/elixir/config.json, languages/elixir/exercises/concept/README.md, languages/elixir/exercises/concept/tuples/.docs/after.md, languages/elixir/exercises/concept/tuples/.docs/hints.md, languages/elixir/exercises/concept/tuples/.docs/instructions.md, languages/elixir/exercises/concept/tuples/.docs/introduction.md, languages/elixir/exercises/concept/tuples/.meta/design.md, languages/elixir/exercises/concept/tuples/test/kitchen_calculator_test.exs, languages/elixir/reference/README.md
I have opened this PR on a new branch to provide some improvements/revisions to the tuple exercise.
=> [Elixir] Improve concept exercise: tuples

reference/stories/README.md, reference/stories/_sidebar.md, reference/stories/strings.high-school-sweethearts.md, reference/types/string.md
This is a story that I came up with for the `strings` exercise in Elixir. Now I am adding it to the stories for other tracks to reuse.
=> Add story for strings: High school sweethearts

languages/rust/config.json
=> [Rust] configure entry-api exercise

docs/concept-exercises.md
This PR clarifies some unspecified rules regarding tasks.
=> [Docs] Clarify task rules in documentation

languages/elixir/config.json, languages/elixir/exercises/concept/README.md, languages/elixir/exercises/concept/multiple-clause-functions/.docs/after.md, languages/elixir/exercises/concept/multiple-clause-functions/.docs/hints.md, languages/elixir/exercises/concept/multiple-clause-functions/.docs/instructions.md, languages/elixir/exercises/concept/multiple-clause-functions/.docs/introduction.md, languages/elixir/exercises/concept/multiple-clause-functions/.formatter.exs, languages/elixir/exercises/concept/multiple-clause-functions/.gitignore, languages/elixir/exercises/concept/multiple-clause-functions/.meta/config.json, languages/elixir/exercises/concept/multiple-clause-functions/.meta/design.md, languages/elixir/exercises/concept/multiple-clause-functions/.meta/example.ex, languages/elixir/exercises/concept/multiple-clause-functions/lib/guessing_game.ex, languages/elixir/exercises/concept/multiple-clause-functions/mix.exs, languages/elixir/exercises/concept/multiple-clause-functions/test/guessing_game_test.exs, languages/elixir/exercises/concept/multiple-clause-functions/test/test_helper.exs, languages/elixir/reference/README.md, reference/stories/pattern-matching.number-guessing-game.md
Initial design review for the concept exercise: multiple-clause-functions
resolves #1365
=> [Elixir] New Concept Exercise: multiple-clause-functions

languages/java/reference/README.md
Proposal for the list of for Java Concepts inspired by the C# ones
=> [Java] Java concepts list

languages/rust/config.json
=> [Rust] configure other concept exercises

languages/fsharp/exercises/concept/numbers/.docs/after.md
=> [F#] Add underscore notation to numbers exercise

languages/csharp/exercises/concept/numbers/.docs/after.md
=> [C#] Add digit separator notation to numbers exercise

languages/elixir/exercises/concept/anonymous-functions/test/secrets_test.exs, languages/elixir/exercises/concept/basics/test/lasagna_test.exs, languages/elixir/exercises/concept/conditionals/test/log_level_test.exs, languages/elixir/exercises/concept/maps/test/high_score_test.exs, languages/elixir/exercises/concept/multiple-clause-functions/test/guessing_game_test.exs, languages/elixir/exercises/concept/numbers/test/freelancer_rate_test.exs, languages/elixir/exercises/concept/recursion/test/recursion_test.exs, languages/elixir/exercises/concept/tuples/test/kitchen_calculator_test.exs
Almost all test files didn't have tests marked as pending, so I am fixing that. I also include the commented-out annotation for each first test. This is how it's done in the v2 Elixir track. I am not entirely sure why, but my guess is that this is supposed to suggest that commenting this line out from other test cases will make them run.
=> [Elixir] Mark all but first test cases pending

.github/labeler.yml, README.md, languages/_sidebar.md, languages/swift/README.md, languages/swift/maintainers.md, languages/swift/reference/implementing-a-concept-exercise.md
=> [Swift] Bootstrap track

languages/csharp/reference/README.md
@mikedamay Seeing how you created https://github.com/exercism/v3/issues/1533, I also gone ahead and updated the reference README to include links to issues and implemented exercises.
=> [C#] Add links to issues and exercises from reference

languages/rust/exercises/concept/entry-api/.meta/design.md, languages/rust/exercises/concept/enums/.meta/design.md, languages/rust/exercises/concept/numbers/.meta/design.md, languages/rust/exercises/concept/structs/.meta/design.md
=> [Docs] remove goal from rust design.md

languages/go/exercises/concept/conditionals/.docs/after.md, languages/go/exercises/concept/conditionals/.docs/hints.md, languages/go/exercises/concept/conditionals/.docs/instructions.md, languages/go/exercises/concept/conditionals/.docs/introduction.md, languages/go/exercises/concept/conditionals/.meta/config.json, languages/go/exercises/concept/conditionals/.meta/design.md, languages/go/exercises/concept/conditionals/.meta/example.go, languages/go/exercises/concept/conditionals/conditionals.go, languages/go/exercises/concept/conditionals/conditionals_test.go
@andres-zartab: what is your exercism user name?
Based on PR #752
Issue is #428
=> [Go] Improve concept exercise: conditionals

languages/fsharp/exercises/concept/pattern-matching/.docs/after.md, languages/fsharp/exercises/concept/pattern-matching/.docs/introduction.md
=> [F#] Add syntax highlighting

languages/fsharp/exercises/concept/pattern-matching/.docs/after.md, languages/fsharp/exercises/concept/pattern-matching/.docs/introduction.md
=> [F#] Fix typo in docs of pattern-matching exercise

languages/fsharp/exercises/concept/recursion/.docs/after.md, languages/fsharp/exercises/concept/recursion/.docs/hints.md, languages/fsharp/exercises/concept/recursion/.docs/introduction.md
Inspiration taken from https://github.com/exercism/v3/pull/1515. Thanks go out to @angelikatyborska
=> [F#] Clarify recursion text

languages/csharp/exercises/concept/basics/.docs/instructions.md
=> [C#] fix typo in basics exercise

languages/cpp/config.json, languages/cpp/exercises/concept/README.md, languages/cpp/exercises/concept/strings/.meta/design.md
=> Fixed C++ Concept exercises naming

.github/labeler.yml, README.md, languages/_sidebar.md, languages/nim/README.md, languages/nim/maintainers.md, languages/nim/reference/implementing-a-concept-exercise.md
=> [Nim] Bootstrap track

languages/elixir/config.json, languages/elixir/exercises/concept/README.md, languages/elixir/exercises/concept/charlists/.docs/after.md, languages/elixir/exercises/concept/charlists/.docs/hints.md, languages/elixir/exercises/concept/charlists/.docs/instructions.md, languages/elixir/exercises/concept/charlists/.docs/introduction.md, languages/elixir/exercises/concept/charlists/.formatter.exs, languages/elixir/exercises/concept/charlists/.gitignore, languages/elixir/exercises/concept/charlists/.meta/config.json, languages/elixir/exercises/concept/charlists/.meta/design.md, languages/elixir/exercises/concept/charlists/.meta/example.ex, languages/elixir/exercises/concept/charlists/lib/username.ex, languages/elixir/exercises/concept/charlists/mix.exs, languages/elixir/exercises/concept/charlists/test/test_helper.exs, languages/elixir/exercises/concept/charlists/test/username_test.exs
This is a draft for a concept exercise that introduces `charlists` and `case`. I came up with a new story for this exercise. Does the story make sense? Is it simple enough?
=> [Elixir] New concept exercise: `charlists`

languages/elixir/exercises/concept/anonymous-functions/.meta/design.md, languages/elixir/exercises/concept/basics/.meta/design.md, languages/elixir/exercises/concept/booleans/.meta/design.md, languages/elixir/exercises/concept/charlists/.meta/design.md, languages/elixir/exercises/concept/conditionals/.meta/design.md, languages/elixir/exercises/concept/lists/.meta/design.md, languages/elixir/exercises/concept/maps/.meta/design.md, languages/elixir/exercises/concept/multiple-clause-functions/.meta/design.md, languages/elixir/exercises/concept/nil/.meta/design.md, languages/elixir/exercises/concept/numbers/.meta/design.md, languages/elixir/exercises/concept/recursion/.meta/design.md, languages/elixir/exercises/concept/strings/.meta/design.md, languages/elixir/exercises/concept/tuples/.meta/design.md
Following the example set by those PRs: https://github.com/exercism/v3/pull/1551 https://github.com/exercism/v3/pull/1547
=> [Elixir] Trim down `design.md`s by removing repetitive or uninformative sections

languages/java/.gitignore, languages/java/config.json, languages/java/exercises/build.gradle, languages/java/exercises/checkstyle.xml, languages/java/exercises/concept/basics/.docs/after.md, languages/java/exercises/concept/basics/.docs/hints.md, languages/java/exercises/concept/basics/.docs/instructions.md, languages/java/exercises/concept/basics/.docs/introduction.md, languages/java/exercises/concept/basics/.meta/config.json, languages/java/exercises/concept/basics/.meta/design.md, languages/java/exercises/concept/basics/.meta/src/reference/java/Lasagna.java, languages/java/exercises/concept/basics/build.gradle, languages/java/exercises/concept/basics/src/main/java/Lasagna.java, languages/java/exercises/concept/basics/src/test/java/LasagnaTest.java, languages/java/exercises/settings.gradle, languages/python/README.md, reference/stories/basics.lasagna.md
I've done the porting of `basics` exercise from C# track.
Two Java track peculiarity:
* I introduced the same gradle build process we have in v2,
* I used assertj as assertion library as decided some time ago.
=> [Java] concept basics exercise

languages/go/exercises/concept/errors/.docs/after.md, languages/go/exercises/concept/errors/.docs/hints.md, languages/go/exercises/concept/errors/.docs/instructions.md, languages/go/exercises/concept/errors/.docs/introduction.md, languages/go/exercises/concept/errors/.meta/config.json, languages/go/exercises/concept/errors/.meta/design.md, languages/go/exercises/concept/errors/.meta/sample.go
Fixes #846
A draft of the errors concept ex.
I've gone with something simple like the answer to life from Hitchhiker's guide to the galaxy. 
The context of the exercise may be changed (suggestions welcome), but I believe it does demonstrate the usage of `error` according to the objectives.
Thoughts?
=> [Go] Add new Concept Exercise: errors

languages/c/reference/exercise-concepts/difference-of-squares.md
=> [C] Extract concepts of v2 difference-of-squares exercise

languages/c/reference/exercise-concepts/hamming.md
=> [C] Extract concepts of v2 hamming exercise

languages/elixir/exercises/concept/charlists/.meta/config.json, languages/elixir/exercises/concept/nil/.meta/config.json, languages/elixir/exercises/concept/numbers/.meta/config.json, languages/elixir/exercises/concept/recursion/.meta/config.json, languages/elixir/exercises/concept/strings/.meta/config.json
Reviewing = contributing. Let's formally give credit where credit is due. In case contributing to building v3 will yield some perks in the future 🤑.
=> [Elixir] Add reviewers of exercises created by me as contributors

languages/elixir/exercises/concept/basics/.meta/config.json, languages/elixir/exercises/concept/binary-matching/.meta/config.json, languages/elixir/exercises/concept/lists/.meta/config.json, languages/elixir/exercises/concept/tuples/.meta/config.json
Just some exercise config updates
=> [Elixir] Attribute others for their work

languages/csharp/exercises/concept/strings/.meta/design.md
Removed an unused link reference in design.md
=> [C#] remove unused link ref

languages/elixir/config.json, languages/elixir/exercises/concept/README.md, languages/elixir/exercises/concept/bitstrings/.docs/after.md, languages/elixir/exercises/concept/bitstrings/.docs/hints.md, languages/elixir/exercises/concept/bitstrings/.docs/instructions.md, languages/elixir/exercises/concept/bitstrings/.docs/introduction.md, languages/elixir/exercises/concept/bitstrings/.formatter.exs, languages/elixir/exercises/concept/bitstrings/.gitignore, languages/elixir/exercises/concept/bitstrings/.meta/config.json, languages/elixir/exercises/concept/bitstrings/.meta/design.md, languages/elixir/exercises/concept/bitstrings/.meta/example.ex, languages/elixir/exercises/concept/bitstrings/lib/dna.ex, languages/elixir/exercises/concept/bitstrings/mix.exs, languages/elixir/exercises/concept/bitstrings/test/dna_test.exs, languages/elixir/exercises/concept/bitstrings/test/test_helper.exs, languages/elixir/reference/README.md, reference/stories/primitive-types.rna-and-dna-processing.md
This a draft PR for introducing a new concept exercise, `bitstrings`
Files provided for initial review:
- introduction.md
- design.md
- example.ex
I think I need to add something in the introduction about using an accumulator for recursion, but I haven't got the wording just yet.
close #1505 
close #1359
=> [Elixir] new concept exercise - bitstrings

languages/ruby/config.json, languages/ruby/exercises/concept/README.md
=> Adjust config.json naming conventions

languages/elixir/config.json, languages/elixir/exercises/concept/README.md, languages/elixir/exercises/concept/structs/.docs/after.md, languages/elixir/exercises/concept/structs/.docs/hints.md, languages/elixir/exercises/concept/structs/.docs/instructions.md, languages/elixir/exercises/concept/structs/.docs/introduction.md, languages/elixir/exercises/concept/structs/.formatter.exs, languages/elixir/exercises/concept/structs/.gitignore, languages/elixir/exercises/concept/structs/.meta/config.json, languages/elixir/exercises/concept/structs/.meta/design.md, languages/elixir/exercises/concept/structs/.meta/example.ex, languages/elixir/exercises/concept/structs/lib/remote_control_car.ex, languages/elixir/exercises/concept/structs/mix.exs, languages/elixir/exercises/concept/structs/test/remote_control_car_test.exs, languages/elixir/exercises/concept/structs/test/test_helper.exs, languages/elixir/reference/README.md, reference/stories/classes.remote-control-car.md
This introduces a new concept exercise to introduce the ideas of structs
Files for draft review:
- .docs
- introduction.md
- .meta
- design.md
- example.ex
While maps is a direct ancestor, I don't think this exercise will occur next in succession be cause of the need for pattern matching, etc prior.  I mention this because that is why I have placed some map function examples in the introduction in reference to structs.
=> [Elixir] new concept exercise: `structs`

languages/ruby/config.json, languages/ruby/exercises/concept/README.md, languages/ruby/exercises/concept/arrays/.docs/after.md, languages/ruby/exercises/concept/arrays/.docs/hints.md, languages/ruby/exercises/concept/arrays/.docs/instructions.md, languages/ruby/exercises/concept/arrays/.docs/introduction.md, languages/ruby/exercises/concept/arrays/.meta/config.json, languages/ruby/exercises/concept/arrays/.meta/design.md, languages/ruby/exercises/concept/arrays/.meta/example.rb, languages/ruby/exercises/concept/arrays/bird_count.rb, languages/ruby/exercises/concept/arrays/bird_count_test.rb
This is the port of the C# arrays' concept exercise to the Ruby track. I added some Ruby specific stuff but I think, in general, the exercise works quite well as it is. Let me know what you think 😄
=> [Ruby] Concept Exercise: arrays

languages/elixir/exercises/concept/exceptions/.docs/introduction.md
I thought the formatting had passed CI check.  Didn't mean to merge with failing CI check.  Sorry.
=> [Elixir] Fix formatting.

languages/elixir/config.json, languages/elixir/exercises/concept/README.md, languages/elixir/exercises/concept/try-rescue-else-after/.docs/after.md, languages/elixir/exercises/concept/try-rescue-else-after/.docs/hints.md, languages/elixir/exercises/concept/try-rescue-else-after/.docs/instructions.md, languages/elixir/exercises/concept/try-rescue-else-after/.docs/introduction.md, languages/elixir/exercises/concept/try-rescue-else-after/.formatter.exs, languages/elixir/exercises/concept/try-rescue-else-after/.gitignore, languages/elixir/exercises/concept/try-rescue-else-after/.meta/config.json, languages/elixir/exercises/concept/try-rescue-else-after/.meta/design.md, languages/elixir/exercises/concept/try-rescue-else-after/.meta/example.ex, languages/elixir/exercises/concept/try-rescue-else-after/lib/rpn_calculator.ex, languages/elixir/exercises/concept/try-rescue-else-after/mix.exs, languages/elixir/exercises/concept/try-rescue-else-after/test/rpn_calculator/output_test.exs, languages/elixir/exercises/concept/try-rescue-else-after/test/test_helper.exs, languages/elixir/reference/README.md
This is a reviewable stub for the `try-rescue-else-after` exercise.  A followup to `errors` building on the same story.
=> [Elixir] new concept exercise `try-rescue-else-after`

reference/stories/tuples.carnival-game.md
I plan to use this as the basis for a simpler tuples concept exercise for the Rust track.
___
I've never heard of this game but I would love to attend the carnival that hosts it. :clown_face:
=> [Docs] story idea for tuples

languages/rust/config.json
Showing off @seanchen1991 's recent work :tada: 
It will up our count in the maintenance [dashboard](https://v3.exercism.io/rust/maintaining/launch) too!
=> [Rust] add concept exercises to our config.json

languages/csharp/exercises/concept/README.md
Nitpicking y'all!
I noticed this failed for my recent PR: https://github.com/exercism/v3/runs/786209009#step:3:6
But it only happened upon merging into master.
=> [docs] fix prettier error for csharp README

README.md, languages/README.md
=> [Docs] Update language list

.github/workflows/update-summary-languages.yml, .github/workflows/update-summary-stories.yml
Merging them into one requires adding a step that checks which files have been modified to determine which step to run. I'm not fully convinced it's a nicer solution and I lack the time, so for now let's just rename them.
=> [CI] Rename summary files for better sorting

badges.md
=> Revert "[Docs] add badge"

.gitattributes, .github/CODEOWNERS, .github/bin/concepts/update.sh, .github/bin/languages/update.sh, .github/bin/stories/update.sh
Closes https://github.com/exercism/v3/issues/1756
=> [CI] Use bot annotations for auto-generated files

languages/elixir/exercises/concept/multiple-clause-functions/.docs/instructions.md
=> [Elixir]  Improve Concept Exercise: `multi-function-clauses`

languages/go/config.json, languages/go/exercises/concept/README.md
I've updated the config.json file and also added the latest concept exercises to the list in Readme. Please review.
=> [Go] update config file and Readme #1703

languages/csharp/exercises/concept/numbers/.meta/design.md
Removed unused link reference from `design.md` of numbers concept exercise
=> [C#] remove unused link reference

docs/maintainers/writing-a-concept-exercise-github-issue.md
Fixed the url of the issue template for a new exercise implementation
=> [Docs] refer to the right issue template url

languages/java/config.json, languages/java/exercises/concept/strings/.docs/after.md, languages/java/exercises/concept/strings/.docs/hints.md, languages/java/exercises/concept/strings/.docs/instructions.md, languages/java/exercises/concept/strings/.docs/introduction.md, languages/java/exercises/concept/strings/.meta/config.json, languages/java/exercises/concept/strings/.meta/design.md, languages/java/exercises/concept/strings/.meta/src/reference/java/LogLine.java, languages/java/exercises/concept/strings/build.gradle, languages/java/exercises/concept/strings/src/main/java/LogLine.java, languages/java/exercises/concept/strings/src/test/java/LogLineTest.java, languages/java/exercises/settings.gradle, reference/stories/strings.log-line-parser.md
Porting of strings exercise from C# track
=> [Java] strings concept exercise

languages/elixir/config.json, languages/elixir/exercises/concept/README.md, languages/elixir/exercises/concept/list-comprehensions/.docs/after.md, languages/elixir/exercises/concept/list-comprehensions/.docs/hints.md, languages/elixir/exercises/concept/list-comprehensions/.docs/instructions.md, languages/elixir/exercises/concept/list-comprehensions/.docs/introduction.md, languages/elixir/exercises/concept/list-comprehensions/.formatter.exs, languages/elixir/exercises/concept/list-comprehensions/.gitignore, languages/elixir/exercises/concept/list-comprehensions/.meta/config.json, languages/elixir/exercises/concept/list-comprehensions/.meta/design.md, languages/elixir/exercises/concept/list-comprehensions/.meta/example.ex, languages/elixir/exercises/concept/list-comprehensions/lib/boutique_suggestions.ex, languages/elixir/exercises/concept/list-comprehensions/mix.exs, languages/elixir/exercises/concept/list-comprehensions/test/boutique_suggestions_test.exs, languages/elixir/exercises/concept/list-comprehensions/test/test_helper.exs, languages/elixir/reference/README.md, reference/stories/enumerable.fashion-boutique.md
This is a draft for an exercise about comprehensions focusing on list comprehensions.
The scope of the exercise will focus on using a list of maps to generate values into a list structure.
I think there is room for a followup exercise using the :into block to use other collectables.  And another for using bitstring generators.
=> [Elixir] new concept exercise - `list-comprehensions`

languages/common-lisp/exercises/concept/basics/.docs/instructions.md
Just a tiny tweak to remove the sterotype of mums' roles as parents :)
=> Remove gender stereotype

languages/x86-64-assembly/exercises/concept/basics/.docs/instructions.md, languages/x86-64-assembly/exercises/concept/basics/.docs/introduction.md, languages/x86-64-assembly/exercises/concept/basics/Makefile, languages/x86-64-assembly/exercises/concept/basics/basics.asm, languages/x86-64-assembly/exercises/concept/basics/basics_test.c
I know this is far from complete, and I'm not looking for a review of the files committed just yet.
What I'm interested in is if this is a good fit for a first exercise of the x86-64 assembly track or not.
Could you try to complete the exercise using the provided `introductions.md`. Is this too much to handle for a first exercise in assembly? Would a beginner be able to complete the exercise in 10-15 minutes? I don't want to put too much work into this before getting these questions answered.
To try out the exercise, you'll need to install `gcc`, `make`, and `nasm`.
Just edit the file `basics.asm` and type `make` to run the tests.
=> [WIP] [x86-64-assembly] Add basics exercise

languages/ruby/exercises/concept/basics/lasagna.rb, languages/swift/exercises/concept/basics/Tests/BasicsTests/BasicsTests.swift
Found a small typo in function name for basics exercise.
=> correct typo 

languages/julia/exercises/concept/unicode-identifiers/.meta/config.json
@cmcaine Sorry, I forgot to add you to the config file in #1589
=> [Julia] unicode-identifiers: Add missing author

reference/stories/booleans.rpg-quest-logic.md
I always forget about these files.
=> [Stories] booleans.rpg: Add Julia implementation

.github/CODEOWNERS
Otherwise nobody will be tagged for PRs (e.g. in #1841) adding stories while they still require a review.
=> Add stories CODEOWNER

languages/fsharp/exercises/concept/basics/.docs/instructions.md, languages/julia/exercises/concept/functions-introduction/.docs/instructions.md, languages/swift/exercises/concept/basics/.docs/instructions.md, languages/x86-64-assembly/exercises/concept/basics/.docs/instructions.md
#1852 It's my first time using GitHub so I hope I didn't screw anything up :>
=> Fix lasasgna

languages/python/exercises/concept/strings/strings.py
=> rearrange functions to match instructions

languages/elixir/exercises/concept/binary-matching/.docs/introduction.md
=> fix missing link

languages/go/config.json
=> move "basics" to prerequisites

languages/x86-64-assembly/exercises/concept/basics/.docs/after.md, languages/x86-64-assembly/exercises/concept/basics/.docs/hints.md, languages/x86-64-assembly/exercises/concept/basics/.docs/instructions.md, languages/x86-64-assembly/exercises/concept/basics/.docs/introduction.md, languages/x86-64-assembly/exercises/concept/basics/.meta/config.json, languages/x86-64-assembly/exercises/concept/basics/.meta/design.md, languages/x86-64-assembly/exercises/concept/basics/.meta/example.asm, languages/x86-64-assembly/exercises/concept/basics/basics.asm, languages/x86-64-assembly/exercises/concept/basics/basics_test.c
I think I've got everything needed to finish up the basics exercise.
Could you take a look @ErikSchierboom ?
=> [x86-64-assembly] Update basics exercise

languages/python/exercises/concept/lists/.docs/instructions.md, languages/python/exercises/concept/lists/.meta/example.py, languages/python/exercises/concept/lists/lists.py, languages/python/exercises/concept/lists/lists_test.py
Ran Prettier to auto-format the markdown in instructions.
=> [Python] Ran Prettier on instructions.md for Lists Concept exercise.

languages/go/config.json
This is an extension to #1703 (https://github.com/exercism/v3/issues/1703#issuecomment-650350196)
Following the list of exercises and the static tree graph from [here](https://github.com/exercism/v3/issues/212) I've added an entry for each exercise in order to generate the dynamic tree.
Please review and let me know your thoughts.
=> [Go]Update config.json with all exercise concepts

languages/csharp/exercises/concept/time/.docs/instructions.md
=> [C#] time - Update instructions.md

languages/go/config.json
My bad... I wanted to go the easy way and just look at the updated tree... but it had circle dependencies and did not draw.
So, here another PR with some changes I would make and the reasoning behind.
=> [Go] Some exercise tree changes to be discussed

languages/elixir/exercises/concept/enum/.docs/instructions.md
It came up in https://github.com/exercism/v3/pull/1928#discussion_r453213417 that many people might have never heard about Black Friday.
=> [Elixir] Improve exercise: `enum` - Remove USA-centric reference

.github/workflows/valid-files.yml
=> [CI] Skip file size check for auto-generated files

languages/scala/exercises/concept/basics/.docs/instructions.md, languages/scala/exercises/concept/basics/.docs/introduction.md, languages/scala/exercises/concept/basics/.meta/Example.scala, languages/scala/exercises/concept/basics/.meta/config.json, languages/scala/exercises/concept/basics/.meta/design.md, languages/scala/exercises/concept/basics/Lasagna.scala, languages/scala/exercises/concept/basics/LasagnaTest.scala, reference/concepts/immutability.md, reference/concepts/type_inference.md, reference/concepts/variables.md
Since this is my first concept, any feedback is welcome (I mean feedback is always appreciated ... but here even more).
Not part of this PR:
* `after.md`
* `hints.md`
=> [Scala] basics new exercise

languages/python/exercises/concept/strings/.docs/instructions.md
=> [Python] specify function names

languages/ruby/reference/README.md
A little bit of tidying based on my experience with Ruby, and @kotp's comments on the PR.
- Remove IO as it's out of scope of Exercism (We don't have things that interact with the stdin/out as a general rule)
- Remove for loops as I've never seen on in production
- Moved some things from advanced classes to general classes, and moved the blocks closer in this file
@biancapower Discussion welcome if you disagree! :)
=> [Ruby] Update Ruby Concepts list

languages/go/config.json, languages/go/exercises/concept/structs/.docs/instructions.md, languages/go/exercises/concept/structs/.meta/config.json, languages/go/exercises/concept/structs/.meta/example.go, languages/go/exercises/concept/structs/structs.go
This is the start for the `structs` exercise. Would like to get this merged, so someone else can fill in the gaps and/or improve based on it. Hope that brings down the hurdle to get started.
Issue for exercise: #2029
=> [Go] structs exercise (started)

languages/ruby/config.json, languages/ruby/exercises/concept/README.md, languages/ruby/exercises/concept/instance-variables/.docs/after.md, languages/ruby/exercises/concept/instance-variables/.docs/hints.md, languages/ruby/exercises/concept/instance-variables/.docs/instructions.md, languages/ruby/exercises/concept/instance-variables/.docs/introduction.md, languages/ruby/exercises/concept/instance-variables/.meta/config.json, languages/ruby/exercises/concept/instance-variables/.meta/design.md, languages/ruby/exercises/concept/instance-variables/.meta/example.rb, languages/ruby/exercises/concept/instance-variables/attendee.rb, languages/ruby/exercises/concept/instance-variables/attendee_test.rb, reference/stories/classes.amusement-park.md
So after taking the reviews and feedback about #1953, I think it's worthwhile to give this a clean slate.
Thoughts:
- In ruby, organizing code in classes is so central to idiomatic code that instance variables must appear very early.
- Trying to model ride passes as we were in #1953 without being able to using instances was constricting good design
- This attempts to then reorganize this progression such that:
- This exercise follows basics
- This exercise teaches about instance variables, getters, and setters
- This exercise will teach about method naming
- This exercise will teach about nil, from the perspective that it is the default value of instance variables before they are assigned
This exercise will have a part 2, which will then teach about booleans (true/false) and truthy-ness. …
=> [Ruby] new concept exercise - `instance-variables`

languages/go/config.json
Shall we quickly test your theory, @TheLostLambda?
=> test uuid = null on tree

languages/go/config.json
Follow-up on https://github.com/exercism/v3/pull/1948
@tehsphinx I've made some changes to the config.json file and I think the tree looks more natural now :) 
I've duplicated Tim's codepen and changed the code to use this latests config.json file so we can have a preview before merging the changes:
[https://codepen.io/anaOM/pen/NWxEepe](https://codepen.io/anaOM/pen/NWxEepe )
Please let me know your thoughts on this.
=> [Go] update config.json and tree

languages/kotlin/exercises/concept/basics/.docs/after.md, languages/kotlin/exercises/concept/basics/.docs/hints.md, languages/kotlin/exercises/concept/basics/.docs/instructions.md, languages/kotlin/exercises/concept/basics/.docs/introduction.md, languages/kotlin/exercises/concept/basics/.meta/src/main/kotlin/Example.kt
Applied suggested fixes from review.
Follow-up issues: #2068, #2069
=> [Kotlin] #1716. Post-review fixes for concept exercise `basic`

languages/common-lisp/bin/generate-scaffolding/template/.meta/example.lisp, languages/common-lisp/config.json, languages/common-lisp/exercises/concept/arithmetic/.docs/after.md, languages/common-lisp/exercises/concept/arithmetic/.docs/hints.md, languages/common-lisp/exercises/concept/arithmetic/.docs/instructions.md, languages/common-lisp/exercises/concept/arithmetic/.docs/introduction.md, languages/common-lisp/exercises/concept/arithmetic/.meta/config.json, languages/common-lisp/exercises/concept/arithmetic/.meta/design.md, languages/common-lisp/exercises/concept/arithmetic/.meta/example.lisp, languages/common-lisp/exercises/concept/arithmetic/arithmetic-test.lisp, languages/common-lisp/exercises/concept/arithmetic/arithmetic.lisp
Things are ready for review! I'll ping @ErikSchierboom for a final pass on this PR when he has the time.
Things I'm thinking of opening a tracking issue for:
- ~Adding LaTeX equations for each of the tasks so that the focus is on implementing the equations and not finding them~
- ~Take another look at [these guidelines ](https://github.com/exercism/v3/blob/master/docs/concept-exercises.md) and give it a pedantic pass for compliance~
For now, this closes #1034
Todo:
=> [Common Lisp] Add new concept exercise: arithmetic

languages/go/exercises/concept/methods/.docs/instructions.md, languages/go/exercises/concept/methods/.meta/config.json, languages/go/exercises/concept/methods/.meta/design.md, languages/go/exercises/concept/methods/.meta/example.go, languages/go/exercises/concept/methods/go.mod, languages/go/exercises/concept/methods/methods.go
A possible start for the `methods` exercise. It takes up the previous exercise (`structs`) and converts some of it's logic to be written as methods. Then some more methods are added.
The advantage of this is that the student can compare the approaches and see the subtle differences, and maybe advantages/disadvantages.
The disadvantage might be that some get bored from the same story again...?
Thoughts: @ErikSchierboom, @oanaOM?
=> [Go] create new concept exercise: methods (start)

languages/common-lisp/exercises/concept/sameness/.docs/hints.md, languages/common-lisp/exercises/concept/sameness/.docs/instructions.md, languages/common-lisp/exercises/concept/sameness/.meta/design.md, languages/common-lisp/exercises/concept/sameness/.meta/example.lisp, languages/common-lisp/exercises/concept/sameness/sameness-test.lisp, languages/common-lisp/exercises/concept/sameness/sameness.lisp
- Fixes #2063
- Fixes #2064
- Fixes #2065
- Fixes #2066
- Fixes #2067
=> [Common Lisp] Sameness Concept Exercise cleanups

languages/common-lisp/config.json
=> [Common Lisp] Fix a silly loop in the dependencies

reference/stories/datetimes.time-keeper.md
Thought I make a story about my actual job. We create hardware and software for time-keepers.
Just in case someone's wondering: https://www.raceresult.com/en-uk/home/index.php
=> [ALL] new time keeper story for duration exercises

languages/swift/maintainers.md
@wneumann @ErikSchierboom  add me as a maintainer for swift lang
=> Add 'haunshila' as a maintainer

languages/ruby/config.json
This is needed while all the tracks are in this monorepo. It can be deleted once they're expanded back out.
=> [Ruby] Add slug to config.json

languages/c/config.json, languages/clojure/config.json, languages/common-lisp/config.json, languages/cpp/config.json, languages/csharp/config.json, languages/dart/config.json, languages/elixir/config.json, languages/elm/config.json, languages/emacs-lisp/config.json, languages/erlang/config.json, languages/fsharp/config.json, languages/go/config.json, languages/haskell/config.json, languages/j/config.json, languages/java/config.json, languages/javascript/config.json, languages/julia/config.json, languages/kotlin/config.json, languages/nim/config.json, languages/purescript/config.json, languages/python/config.json, languages/ruby/config.json, languages/rust/config.json, languages/scala/config.json, languages/swift/config.json, languages/x86-64-assembly/config.json
Bash worked 🤷 
```bash
for d in */; do d=${d/\//}; head -n 2 "$d/config.json" > tmp.json; echo "  \"slug\": \"$d\"," >> tmp.json; tail -n +3  "$d/config.json" >> tmp.json; mv tmp.json "$d/config.json"; done
```
=> Add slugs to configs

languages/csharp/exercises/concept/classes/.docs/after.md
=> [C#] classes - typo

languages/nim/reference/exercise-concepts/protein-translation.md
I finally got over the "which should I choose to get this 💯 % right" hump and just chose one!!!!
=> [Nim] Extract concepts from protein-translation

languages/csharp/config.json, languages/csharp/exercises/concept/arrays/.meta/design.md, languages/csharp/exercises/concept/chars/.meta/design.md, languages/csharp/exercises/concept/classes/.meta/design.md, languages/csharp/exercises/concept/constructors/.meta/design.md, languages/csharp/exercises/concept/enums/.meta/design.md, languages/csharp/exercises/concept/expression-bodied-members/.meta/design.md, languages/csharp/exercises/concept/floating-point-numbers/.meta/design.md, languages/csharp/exercises/concept/inheritance/.meta/design.md, languages/csharp/exercises/concept/nullability/.meta/design.md, languages/csharp/exercises/concept/numbers/.meta/design.md, languages/csharp/exercises/concept/parameters/.meta/design.md, languages/csharp/exercises/concept/time/.meta/design.md, languages/csharp/exercises/concept/tuples/.meta/design.md, languages/csharp/exercises/concept/user-defined-exceptions/.meta/design.md, languages/csharp/reference/exercises.json
allocated to exercises some unallocated concepts on exercise-report README.md
=> [C#] clean-concepts - allocated some unallocated concepts

languages/common-lisp/config.json, languages/common-lisp/exercises/concept/conditionals/.docs/after.md, languages/common-lisp/exercises/concept/conditionals/.docs/hints.md, languages/common-lisp/exercises/concept/conditionals/.docs/instructions.md, languages/common-lisp/exercises/concept/conditionals/.docs/introduction.md, languages/common-lisp/exercises/concept/conditionals/.meta/config.json, languages/common-lisp/exercises/concept/conditionals/.meta/design.md, languages/common-lisp/exercises/concept/conditionals/.meta/example.lisp, languages/common-lisp/exercises/concept/conditionals/conditionals-test.lisp, languages/common-lisp/exercises/concept/conditionals/conditionals.lisp
Eventually closes #1012, just a tracking PR for now.
=> [Common Lisp] Implement new Concept Exercise: conditionals

docs/maintainers/repository-structure.md
This label is for issues that are not actionable until the track is close to launch.
=> [Docs] Add label: type/launch-checklist

languages/csharp/exercises/concept/interfaces/.docs/after.md
=> [C#] Update after.md

languages/java/config.json, languages/java/exercises/concept/classes/.docs/after.md, languages/java/exercises/concept/classes/.docs/hints.md, languages/java/exercises/concept/classes/.docs/instructions.md, languages/java/exercises/concept/classes/.docs/introduction.md, languages/java/exercises/concept/classes/.meta/config.json, languages/java/exercises/concept/classes/.meta/design.md, languages/java/exercises/concept/classes/.meta/src/reference/java/RemoteControlCar.java, languages/java/exercises/concept/classes/build.gradle, languages/java/exercises/concept/classes/src/main/java/RemoteControlCar.java, languages/java/exercises/concept/classes/src/test/java/RemoteControlCarTest.java
All files complete except java/config.json and exercises/settings.gradle which I will update before merging
=> [Java] classes - new exercise

languages/csharp/config.json, languages/csharp/exercises/concept/flag-enums/.meta/design.md, languages/csharp/exercises/concept/integral-numbers/.meta/design.md, languages/csharp/exercises/concept/parameters/.meta/design.md, languages/csharp/reference/exercises.json
addressed part of issue #2250.  Fixed items that appeared in config.json but not in exercises.json
=> [C#] issue #2250 mismatch between exercises.json and config.json

languages/java/exercises/concept/classes/src/test/java/RemoteControlCarTest.java
https://github.com/exercism/v3/issues/2252
=> java: changed tests to use assertj

languages/erlang/exercises/concept/README.md
A new pr to merge #1166 from a branch on the repo rather than a fork.
=> [Erlang] add concept exercises README.md

languages/java/exercises/concept/interfaces/src/test/java/RemoteControlCarTest.java
https://github.com/exercism/v3/issues/2267
=> Changes to assertj assertions.

languages/java/exercises/concept/arrays/build.gradle, languages/java/exercises/concept/basics/build.gradle, languages/java/exercises/concept/booleans/build.gradle, languages/java/exercises/concept/chars/build.gradle, languages/java/exercises/concept/classes/build.gradle, languages/java/exercises/concept/conditionals/build.gradle, languages/java/exercises/concept/constructors/build.gradle, languages/java/exercises/concept/interfaces/build.gradle, languages/java/exercises/concept/numbers/build.gradle, languages/java/exercises/concept/strings/build.gradle, languages/java/exercises/concept/ternary-operators/build.gradle
Port to v3 exercises a fix from the v2  java track to address this https://github.com/exercism/exercism/issues/5353
=> [Java] add UTF-8 encoding into gradle config

reference/stories/optionals.pizza-slices.md, reference/types/option_types.md
Also adding option_types.md to reference/types
=> [Docs] Adding Pizza Slice story for Optional types

reference/stories/strings-and-characters.custom-signs.md, reference/types/character.md
Added Custom Signs story used in the Swift track's strings-and-characters exercise
Also added unicode character type
=> [Docs] Added Custom Signs story

reference/stories/structs-and-classes.windowing-system.md, reference/types/struct.md
Added the windowing system story used in Swift's structs-and-classes concept exercise
Modified types/struct.md to add information beyond simple record-style structs, now mirrors types/class.md
=> [Docs] Add Windowing System story

reference/concepts/enumeration.md, reference/stories/loops.bartender.md
Added bartender story used in Swift track's loops concept exercise
Modified concepts/enumeration to include this story
=> [Docs] Added Bartender story, 

reference/types/tuple.md
split implementations table so that there is one per unique story
=> [Docs] Update types/tuple.md

reference/concepts/anonymous_functions.md, reference/stories/anonymous-functions.bomb-disarming.md
Added Bomb Disarming story used in Swift track's closures concept exercise
Modified concepts/anonymous_functions.md
=> [Docs] Added Bomb Disarming / closures story

languages/python/exercises/concept/enums/.docs/after.md, languages/python/exercises/concept/enums/.docs/hints.md, languages/python/exercises/concept/enums/.docs/instructions.md, languages/python/exercises/concept/enums/.docs/introduction.md, languages/python/exercises/concept/enums/.meta/config.json, languages/python/exercises/concept/enums/.meta/design.md, languages/python/exercises/concept/enums/.meta/example.py, languages/python/exercises/concept/enums/enums.py, languages/python/exercises/concept/enums/enums_test.py
I refered Erik's Csharp Exercise as suggested and used his example and added extra functions over it. As mentioned I didnt go into more advanced topics as Flags, IntEnums etc.
=> [Python] Implement new Concept Exercise: Enum #2309

languages/elixir/concepts/atoms/about.md, languages/elixir/concepts/atoms/links.json
Further updates to atom description.
=> Elixir cond replace after md with concept documents

languages/python/exercises/concept/list_methods/.docs/after.md, languages/python/exercises/concept/list_methods/.docs/hints.md, languages/python/exercises/concept/list_methods/.docs/instructions.md, languages/python/exercises/concept/list_methods/.docs/introduction.md, languages/python/exercises/concept/list_methods/.meta/config.json, languages/python/exercises/concept/list_methods/.meta/design.md, languages/python/exercises/concept/list_methods/.meta/example.py, languages/python/exercises/concept/list_methods/list_methods.py, languages/python/exercises/concept/list_methods/list_methods_test.py
I think this took a long time than the rest :D . There was a lot of ground to cover. 
1. I made sure i was on point in the introduction.md
2. I added around 11 exercises as a whole. ( Because we have that many functions to test )
3. There are around 20 + tests for this exercise.
4. I have spoken about the execeptions which can occur during ( remove , index etc )
5. I have mentioned about `timsort` being used when we called list.sort(). Not sure if its appropriate.
Hope this helps. 👍
=> [Python] Implement new Concept Exercise: list-methods #2170

languages/python/exercises/concept/loops/.docs/after.md, languages/python/exercises/concept/loops/.docs/hints.md, languages/python/exercises/concept/loops/.docs/instructions.md, languages/python/exercises/concept/loops/.docs/introduction.md, languages/python/exercises/concept/loops/.meta/config.json, languages/python/exercises/concept/loops/.meta/design.md, languages/python/exercises/concept/loops/.meta/example.py, languages/python/exercises/concept/loops/loops.py, languages/python/exercises/concept/loops/loops_test.py
Few Comments to Add
1. I need to add more info in after.md.
2. I kept the intro really short and precise. I think it needs more info and well documented.
3. I probably need more testing exercises. will think of some more ( i tested only happy path )
4. @yawpitch  was really good resource. I didnt exactly write the same content but used it as reference as @DavidGerva mentioned.
@BethanyG : Can you review this as well!. Thanks :) !
=> [Python] Implement new Concept Exercise: loops #1430

languages/python/exercises/concept/none/.docs/after.md, languages/python/exercises/concept/none/.docs/hints.md, languages/python/exercises/concept/none/.docs/instructions.md, languages/python/exercises/concept/none/.docs/introduction.md, languages/python/exercises/concept/none/.meta/config.json, languages/python/exercises/concept/none/.meta/design.md, languages/python/exercises/concept/none/.meta/example.py, languages/python/exercises/concept/none/none.py, languages/python/exercises/concept/none/none_test.py
I have written this PR as per the contributing docs. 
Would like @DavidGerva, and someone from the python maintainers to review this PR.
Few points to add:
Although the exercise was just about None, I felt that the way to test the exercise would have been hard without having any reference to the Input.
1. If we expect to return None, a simple pass() statement on the function would also pass the test case.
2. Used a list to manipulate and understand the use of None.
I'm not sure the example for this exercise is appropriate and I am willing to do a full redo if required. Let me know. Thanks.
=> [Python] Implement new Concept Exercise: none #1031

languages/java/concepts/chars/about.md, languages/java/exercises/concept/chars/.docs/after.md
```
<track>
├── concepts
│   └── ...
```
1. Extract the …
=> [Java] chars - replace about.md file with concept files

languages/csharp/config.json, languages/csharp/exercises/concept/switch-statements/.docs/after.md, languages/csharp/exercises/concept/switch-statements/.docs/instructions.md, languages/csharp/exercises/concept/switch-statements/.docs/introduction.md, languages/csharp/exercises/concept/switch-statements/.meta/Example.cs, languages/csharp/exercises/concept/switch-statements/.meta/config.json, languages/csharp/exercises/concept/switch-statements/.meta/design.md, languages/csharp/exercises/concept/switch-statements/SwitchStatements.cs, languages/csharp/exercises/concept/switch-statements/SwitchStatementsTests.cs
Closes #2322
Let me know if anything need to change
=> [C#] remove enum from config and from the switch exercise

languages/python/concepts/bools/about.md, languages/python/concepts/bools/links.json, languages/python/exercises/concept/bools/.docs/introduction.md, languages/python/exercises/concept/bools/.meta/design.md
Added links file and made some small edits to the concept doc and intro docs.
=> Bools:  Add Links and Clean Up Concept Doc

languages/julia/reference/progression.md
=> [Julia] Update Progression Notes

.github/bin/stories/Program.fs
=> [CI] Fix stories generator

.github/workflows/valid-links.yml
=> [CI] Skip link checking for auto-generated files

languages/elixir/exercises/concept/basketball-website/.meta/config.json, languages/elixir/exercises/concept/bird-count/.meta/config.json, languages/elixir/exercises/concept/boutique-inventory/.meta/config.json, languages/elixir/exercises/concept/boutique-suggestions/.meta/config.json, languages/elixir/exercises/concept/bread-and-potions/.meta/config.json, languages/elixir/exercises/concept/community-garden/.meta/config.json, languages/elixir/exercises/concept/date-parser/.meta/config.json, languages/elixir/exercises/concept/dna-encoding/.meta/config.json, languages/elixir/exercises/concept/file-sniffer/.meta/config.json, languages/elixir/exercises/concept/freelance-rate/.meta/config.json, languages/elixir/exercises/concept/german-sysadmin/.meta/config.json, languages/elixir/exercises/concept/guessing-game/.meta/config.json, languages/elixir/exercises/concept/high-school-sweetheart/.meta/config.json, languages/elixir/exercises/concept/high-score/.meta/config.json, languages/elixir/exercises/concept/kitchen-calculator/.meta/config.json, languages/elixir/exercises/concept/language-list/.meta/config.json, languages/elixir/exercises/concept/lasagna/.meta/config.json, languages/elixir/exercises/concept/log-level/.meta/config.json, languages/elixir/exercises/concept/mensch-aergere-dich-nicht/.meta/config.json, languages/elixir/exercises/concept/name-badge/.meta/config.json, languages/elixir/exercises/concept/pacman-rules/.meta/config.json, languages/elixir/exercises/concept/remote-control-car/.meta/config.json, languages/elixir/exercises/concept/rpn-calculator-output/.meta/config.json, languages/elixir/exercises/concept/rpn-calculator/.meta/config.json, languages/elixir/exercises/concept/secrets/.meta/config.json, languages/elixir/exercises/concept/stack-underflow/.meta/config.json, languages/elixir/exercises/concept/take-a-number/.meta/config.json, languages/elixir/exercises/concept/wine-cellar/.meta/config.json
See https://github.com/exercism/v3/issues/2569
=> [Elixir] Add "editor" key to concept exercise configs

languages/common-lisp/exercises/concept/arithmetic/.meta/config.json, languages/common-lisp/exercises/concept/basics/.meta/config.json, languages/common-lisp/exercises/concept/conditionals/.meta/config.json, languages/common-lisp/exercises/concept/lists/.meta/config.json, languages/common-lisp/exercises/concept/sameness/.meta/config.json
=> Add the new editor keys

languages/go/exercises/concept/basics/.meta/config.json, languages/go/exercises/concept/booleans/.meta/config.json, languages/go/exercises/concept/comments/.meta/config.json, languages/go/exercises/concept/conditionals/.meta/config.json, languages/go/exercises/concept/errors/.meta/config.json, languages/go/exercises/concept/maps/.meta/config.json, languages/go/exercises/concept/methods/.meta/config.json, languages/go/exercises/concept/numbers/.meta/config.json, languages/go/exercises/concept/slices/.meta/config.json, languages/go/exercises/concept/strings-package/.meta/config.json, languages/go/exercises/concept/strings/.meta/config.json, languages/go/exercises/concept/structs/.meta/config.json, languages/go/exercises/concept/time/.meta/config.json, languages/go/exercises/concept/zero-value/.meta/config.json
=> [Go] Add "editor" key in concept exercise configs

.github/workflows/julia-exercise-ci.yml, .prettierignore, languages/julia/.gitignore, languages/julia/bin/Manifest.toml, languages/julia/bin/Project.toml, languages/julia/bin/generate-editor-config.jl, languages/julia/config.json, languages/julia/exercises/concept/boolean-logic/.meta/config.json, languages/julia/exercises/concept/emoji-times/.meta/config.json, languages/julia/exercises/concept/encounters/.meta/config.json, languages/julia/exercises/concept/functions-introduction/.meta/config.json, languages/julia/exercises/concept/matrices-introduction/.meta/config.json, reference/stories/basics.lasagna.md, reference/stories/booleans.rpg-quest-logic.md, reference/stories/matrices.exercism-logo-matrix.md
=> [Julia] Add names for all exercises

languages/fsharp/exercises/concept/arrays/.docs/introduction.md, languages/fsharp/exercises/concept/basics/.docs/introduction.md, languages/fsharp/exercises/concept/booleans/.docs/introduction.md, languages/fsharp/exercises/concept/datetimes/.docs/introduction.md, languages/fsharp/exercises/concept/discriminated-unions/.docs/introduction.md, languages/fsharp/exercises/concept/floating-point-numbers/.docs/introduction.md, languages/fsharp/exercises/concept/lists/.docs/introduction.md, languages/fsharp/exercises/concept/numbers/.docs/introduction.md, languages/fsharp/exercises/concept/pattern-matching/.docs/introduction.md, languages/fsharp/exercises/concept/records/.docs/introduction.md, languages/fsharp/exercises/concept/recursion/.docs/introduction.md, languages/fsharp/exercises/concept/strings/.docs/introduction.md
See https://github.com/exercism/v3/issues/2293
=> [F#] Add concept headings to introduction.md

.github/workflows/rebase.yml
Additional details [here](https://github.com/cirrus-actions/rebase/commit/f72b20de85657401499fc29a910469d7663a78dc) and [here](https://bugs.chromium.org/p/project-zero/issues/detail?id=2070&can=2&q=&colspec=ID%20Type%20Status%20Priority%20Milestone%20Owner%20Summary&cells=ids).
=> [CI] Bump rebase action to fix CVE-2020-15228

languages/c/config.json, languages/clojure/config.json, languages/common-lisp/config.json, languages/cpp/config.json, languages/csharp/config.json, languages/dart/config.json, languages/elixir/config.json, languages/elm/config.json, languages/emacs-lisp/config.json, languages/erlang/config.json, languages/fsharp/config.json, languages/go/config.json, languages/haskell/config.json, languages/j/config.json, languages/java/config.json, languages/javascript/config.json, languages/julia/config.json, languages/kotlin/config.json, languages/nim/config.json, languages/perl5/config.json, languages/purescript/config.json, languages/python/config.json, languages/ruby/config.json, languages/rust/config.json, languages/scala/config.json, languages/swift/config.json, languages/x86-64-assembly/config.json
When I imported the practice exercises a while back, I mistakenly added them at the root. They should be placed inside the `exercises` key, which this PR fixes.
=> [All] Move practice exercises inside "exercises" key in config.json

languages/csharp/exercises/concept/international-calling-connoisseur/.docs/introduction.md, languages/csharp/exercises/concept/international-calling-connoisseur/.meta/config.json, languages/csharp/exercises/concept/international-calling-connoisseur/InternationalCallingConnoisseur.cs, languages/csharp/exercises/concept/international-calling-connoisseur/InternationalCallingConnoisseurTests.cs
=> [C#] dictionary ex. tests with only one assert

languages/csharp/exercises/concept/squeaky-clean/.docs/instructions.md, languages/csharp/exercises/concept/squeaky-clean/SqueakyCleanTests.cs
=> [C#] instructions.md for empty string

languages/elixir/concepts/io/about.md, languages/elixir/concepts/io/links.json, languages/elixir/config.json, languages/elixir/exercises/concept/rpg-character-sheet/.docs/hints.md, languages/elixir/exercises/concept/rpg-character-sheet/.docs/instructions.md, languages/elixir/exercises/concept/rpg-character-sheet/.docs/introduction.md, languages/elixir/exercises/concept/rpg-character-sheet/.formatter.exs, languages/elixir/exercises/concept/rpg-character-sheet/.gitignore, languages/elixir/exercises/concept/rpg-character-sheet/.meta/config.json, languages/elixir/exercises/concept/rpg-character-sheet/.meta/design.md, languages/elixir/exercises/concept/rpg-character-sheet/.meta/example.ex, languages/elixir/exercises/concept/rpg-character-sheet/lib/rpg/character_sheet.ex, languages/elixir/exercises/concept/rpg-character-sheet/mix.exs, languages/elixir/exercises/concept/rpg-character-sheet/test/rpg/character_sheet_test.exs, languages/elixir/exercises/concept/rpg-character-sheet/test/test_helper.exs, languages/elixir/exercises/concept/rpn-calculator-output/.meta/design.md, reference/stories/io.rpg-character-sheet.md
Related issue: https://github.com/exercism/v3/issues/2291
I would like to propose defining an `io` concept as a more basic concept, about writing and reading from the standard io device. This knowledge is necessary for basic debugging and for writing scripts that ask for user input.
This is not enough as a prerequisite for the `rpn-calculator-output` exercise, which requires knowledge about opening and closing IO devices, so the dependency of that exercise needs to be renamed, and it will need a different concept exercise.
I have created the example solution, tests, and instructions so far, and will write the rest of the files, including concept descriptions, later, when this story idea is approved.
=> [Elixir] New concept exercise - io

languages/python/config.json
Added back in prerequisites that were not `basics` and tested to make sure there weren't cycles.
=> [Python] Concept Tree Updates

languages/julia/config.json, languages/julia/reference/progression.md
should be rebased, not squash-merged
=> [Julia] Config & Progression updates

languages/csharp/config.json, languages/csharp/exercises/concept/calculator-conundrum/.docs/instructions.md, languages/csharp/exercises/concept/calculator-conundrum/.docs/introduction.md, languages/csharp/exercises/concept/calculator-conundrum/.meta/Example.cs, languages/csharp/exercises/concept/calculator-conundrum/.meta/config.json, languages/csharp/exercises/concept/calculator-conundrum/.meta/design.md, languages/csharp/exercises/concept/calculator-conundrum/CalculatorConundrum.cs, languages/csharp/exercises/concept/calculator-conundrum/CalculatorConundrumTests.cs
Removing cyclic dependency overflow-exceptions.
Remove OverflowException from the Calculator Conundrum exercise.
Various renames.
=> [C#] Csharp/calculator cyclic dep improv 2314

docs/maintainers/determining-concepts.md
Requesting review from @exercism/reviewers
=> [Docs] Specify rules for naming concept exercises

languages/swift/config.json
Adding name key to config.json. 
Removed spurious tuples entry.
=> [Swift] Add name key to config.json

languages/swift/exercises/concept/vehicle-purchase/.docs/instructions.md
Sorry for the PR spam, I'm porting the exercise to Julia and fixing these as I go :D
=> [Swift][vehicle-purchase] typo fixes

languages/csharp/concepts/basics/about.md, languages/csharp/concepts/basics/links.json
- Add some details to the about file.
- Add the link to the identifier rules.
Edit:
- Mentioning the @ escape character
Close #1979
=> [C#] Basics concept. detailing variable names

languages/python/concepts/numbers/about.md, languages/python/concepts/numbers/links.json
*  Added `about.md` for the Numbers concept
*  Added `links.json` for the Numbers concept
=> [Python] Added Numbers Concept Description and Links Files

docs/maintainers/faqs.md
Fixing typo in faqs
> Line 94
prequisites -> prerequisites
=> Fix : fix typo

languages/julia/concepts/conditionals/about.md, languages/julia/concepts/conditionals/links.json, languages/julia/concepts/if-statements/about.md, languages/julia/concepts/if-statements/links.json, languages/julia/concepts/iterator-protocol/about.md, languages/julia/concepts/iterator-protocol/links.json, languages/julia/concepts/optional-arguments/about.md, languages/julia/concepts/optional-arguments/links.json, languages/julia/concepts/short-circuit-evaluation/about.md, languages/julia/concepts/short-circuit-evaluation/links.json, languages/julia/concepts/ternary-operator/about.md, languages/julia/concepts/ternary-operator/links.json, languages/julia/exercises/concept/vehicle-purchase/.docs/introduction.md
This adds concept docs for the exercises introduced in #2764 and #2796. These are mostly extracted from the introduction documents, with minor adjustments to remove references to the exercise.
=> [Julia] Add concept docs for several exercises

docs/maintainers/style-guide.md
Fixes https://github.com/exercism/v3/pull/2844#pullrequestreview-538204931
=> [CI] Update prettier docs

languages/elixir/exercises/concept/basketball-website/test/basketball_website_test.exs, languages/elixir/exercises/concept/boutique-suggestions/test/boutique_suggestions_test.exs, languages/elixir/exercises/concept/bread-and-potions/test/rpg_test.exs, languages/elixir/exercises/concept/rpn-calculator/test/rpn_calculator_test.exs, languages/elixir/exercises/concept/wine-cellar/test/wine_cellar_test.exs
I also ran `mix format` on those, hence the formatting changes.
=> [Elixir] Add missing `@tag :pending` to a few concept exercises

languages/dart/maintainers.md
Request to add me to the list of maintainers
=> [Dart] Add Stargator to list of maintainers

.github/workflows/valid-links.yml
This reverts commit 18abce10b940d65aac810bb35cade793e914acd4.
=> Revert "[CI] Enable external link checks (#2881)"

.github/workflows/valid-files.yml
Added `languages/python/reference/README.md` to exceptions for file size.
=> Update valid-files.yml to except languages/python/reference/README.md

languages/csharp/concepts/inheritance/about.md, languages/csharp/exercises/concept/wizards-and-warriors/.docs/introduction.md, languages/csharp/exercises/concept/wizards-and-warriors/.meta/design.md, languages/csharp/reference/exercises.json
Included the `polymorphism` concept as part of `inheritance`.
=> [C#] polymorphism concept

languages/julia/exercises/concept/fibonacci-iterator/.docs/hints.md
Inspired by @miguelraz writing a fib iterator on his stream.
=> [Julia] fibonacci-iterator: Add hints

languages/python/exercises/concept/elyses-enchantments/.docs/introduction.md
I corrected markdown syntax so that links can be properly linked.
=> [Python] Fix markdown

languages/python/reference/implementing-a-concept-exercise.md
Updated/edited `languages/python/reference/implementing-a-concept-exercise.md`.
=> [Python] Updates to implementing-a-concept-exercise.md

languages/elixir/exercises/concept/bread-and-potions/.meta/config.json, languages/elixir/exercises/concept/captains-log/.meta/config.json, languages/elixir/exercises/concept/rpg-character-sheet/.meta/config.json, languages/elixir/exercises/concept/wine-cellar/.meta/config.json
We've been talking about reputation on the last call, which reminded me that I wasn't consistent with filling out the "contributors" field. Tim reviewed **all** the exercises that I created and needs to be listed as a contributor.
=> [Elixir] Add neenjaw as contributor to my exercises that he reviewed

languages/elixir/exercises/concept/wine-cellar/test/wine_cellar_test.exs
=> [Elixir] Ensure that tests are self-contained - `wine-cellar`

languages/elixir/exercises/concept/basketball-website/.meta/example.ex, languages/elixir/exercises/concept/basketball-website/test/basketball_website_test.exs
Deleted module attribute and ran `mix format`.
=> [Elixir] Ensure that tests are self-contained - `basketball-website`

languages/elixir/exercises/concept/boutique-suggestions/.meta/example.ex, languages/elixir/exercises/concept/boutique-suggestions/test/boutique_suggestions_test.exs
This PR removes module attributes and runs `mix format`.
=> [Elixir] Ensure that tests are self-contained - `boutique-suggestions`

languages/elixir/exercises/concept/high-score/test/high_score_test.exs
This PR removes the module attributes.
=> [Elixir] Ensure that tests are self-contained - `high-score`

languages/javascript/concepts/recursion/about.md
```
<track>
├── concepts
│   └── ...
```
1. Extract the …
=> [JavaScript] recursion - replace about.md file with concept files

languages/fsharp/exercises/concept/annalyns-infiltration/AnnalynsInfiltration.fsproj, languages/fsharp/exercises/concept/bandwagoner/Bandwagoner.fsproj, languages/fsharp/exercises/concept/bird-watcher/BirdWatcher.fsproj, languages/fsharp/exercises/concept/booking-up-for-beauty/BookingUpForBeauty.fsproj, languages/fsharp/exercises/concept/cars-assemble/CarsAssemble.fsproj, languages/fsharp/exercises/concept/guessing-game/GuessingGame.fsproj, languages/fsharp/exercises/concept/interest-is-interesting/InterestIsInteresting.fsproj, languages/fsharp/exercises/concept/log-levels/LogLevels.fsproj, languages/fsharp/exercises/concept/lucians-luscious-lasagna/LuciansLusciousLasagna.fsproj, languages/fsharp/exercises/concept/pizza-pricing/PizzaPricing.fsproj, languages/fsharp/exercises/concept/tracks-on-tracks-on-tracks/TracksOnTracksOnTracks.fsproj, languages/fsharp/exercises/concept/valentines-day/ValentinesDay.fsproj
In combination with https://github.com/exercism/fsharp-test-runner/pull/10, this will update our F# exercises to .NET 5.
=> [F#] Upgrade to .NET 5

languages/elixir/exercises/concept/secrets/.docs/instructions.md, languages/elixir/exercises/concept/secrets/.docs/introduction.md, languages/elixir/exercises/concept/secrets/.meta/example.ex, languages/elixir/exercises/concept/secrets/lib/secrets.ex
As I was solving this exercise without peaking into the example solution, I had some issues figuring out the order of arguments that I'm supposed to use in the anonymous functions that I am creating.
E.g. when I read the first step "have it return a function which takes one argument and adds it to the argument passed in to secret_add", I wrote `secret + x`. Then I read the second step: "have it return a function which takes one argument and subtracts the argument passed in to `secret_subtract`.", I couldn't deduct what is supposed to be subtracted from what, so I wrote `secret - x` assuming it's the same order as in the first step. That was wrong.
To fix this, I rephrased the instructions to always have a preposition ("subtracts from"), to always mention the arguments in the same order …
=> [Elixir] Improve the `secrets` exercise

languages/elixir/exercises/concept/guessing-game/.docs/instructions.md, languages/elixir/exercises/concept/guessing-game/.meta/example.ex, languages/elixir/exercises/concept/guessing-game/test/guessing_game_test.exs
As I was solving this exercise on my own without peeking into the example solution, I noticed that I can solve it without ever even considering using default arguments. I think this one additional test will help with that.
=> [Elixir] In `guessing-game`, nudge the user into actually using default arguments

languages/elixir/exercises/concept/basketball-website/.docs/hints.md, languages/elixir/exercises/concept/bird-count/.docs/hints.md, languages/elixir/exercises/concept/boutique-inventory/.docs/hints.md, languages/elixir/exercises/concept/boutique-suggestions/.docs/hints.md, languages/elixir/exercises/concept/community-garden/.docs/hints.md, languages/elixir/exercises/concept/date-parser/.docs/hints.md, languages/elixir/exercises/concept/dna-encoding/.docs/hints.md, languages/elixir/exercises/concept/freelancer-rates/.docs/hints.md, languages/elixir/exercises/concept/german-sysadmin/.docs/hints.md, languages/elixir/exercises/concept/guessing-game/.docs/hints.md, languages/elixir/exercises/concept/high-school-sweetheart/.docs/hints.md, languages/elixir/exercises/concept/language-list/.docs/hints.md, languages/elixir/exercises/concept/mensch-aergere-dich-nicht/.docs/hints.md, languages/elixir/exercises/concept/name-badge/.docs/hints.md, languages/elixir/exercises/concept/newsletter/.docs/hints.md, languages/elixir/exercises/concept/pacman-rules/.docs/hints.md, languages/elixir/exercises/concept/remote-control-car/.docs/hints.md, languages/elixir/exercises/concept/rpg-character-sheet/.docs/hints.md, languages/elixir/exercises/concept/rpn-calculator-output/.docs/hints.md, languages/elixir/exercises/concept/rpn-calculator/.docs/hints.md, languages/elixir/exercises/concept/secrets/.docs/hints.md, languages/elixir/exercises/concept/stack-underflow/.docs/hints.md, languages/elixir/exercises/concept/take-a-number/.docs/hints.md, languages/elixir/exercises/concept/wine-cellar/.docs/hints.md
I noticed that the guessing game's hints don't work, so I went and reviewed all the hint files:
- Make sure every hint section is a list
- Remove nested lists, they do not render on exercism.lol
- Make sure every hint consists of one or more sentences (capitalized, ends with a dot).
I didn't double-check if the hints' headers are the same as in introduction. I hope somebody else will make a tool for that soon.
=> [Elixi] Fix hints for all exercises

languages/common-lisp/exercises/concept/lillys-lasagna-leftovers/lillys-lasagna-leftovers-test.lisp
This PR adds descriptions to each test.
Fixes #2966
=> [Common Lisp] Adding test descriptions for lillys-lasagna-leftover exercise

languages/elixir/concepts/binaries/introduction.md, languages/elixir/exercises/concept/file-sniffer/.docs/introduction.md, languages/elixir/exercises/concept/file-sniffer/.meta/example.ex, languages/elixir/exercises/concept/file-sniffer/test/file_sniffer_test.exs
This PR:
- Rewords the introduction a bit.
- Removes repetitive links from the introduction because we were supposed to keep links to the minimum there 🙊
- Fixes the return values of the functions that need implementing to match instructions
- `mix format`
=> [Elixir] Improve exercise `file-sniffer`

languages/elixir/concepts/access-behaviour/introduction.md, languages/elixir/exercises/concept/basketball-website/.docs/instructions.md, languages/elixir/exercises/concept/basketball-website/.docs/introduction.md
Tiny rewording of the `access-behavior` introduction.
=> [Elixir] Improve concept exercise `basketball-website`

languages/elixir/concepts/list-comprehensions/about.md, languages/elixir/exercises/concept/boutique-suggestions/.docs/instructions.md
Beautiful exercise, almost nothing to fix :)
=> [Elixir] Improve exercise `boutique-suggestions`

languages/julia/config.json
This is a mix of @cmcaine and I's comments in #2763, as well as the feature boxes on [julialang.org](https://julialang.org/):
- https://github.com/exercism/v3/issues/2763#issuecomment-724792070
- https://github.com/exercism/v3/issues/2763#issuecomment-725050854
=> [Julia] Add tags & key_features

languages/elixir/config.json
Key features as defined by Tim in https://github.com/exercism/v3/issues/2763#issuecomment-724947819 (+ a 6th one, "general-purpose").
=> [Elixir] Add tags and key features

languages/julia/config.json
This no longer requires boolean expressions, only booleans. Forgot to fix after addressing the changes in #3063
=> [Julia] annalyn2: fix pre-reqs

languages/ruby/exercises/concept/conditionals-ternary/.docs/instructions.md, languages/ruby/exercises/concept/conditionals-ternary/.docs/introduction.md, languages/ruby/exercises/concept/conditionals-ternary/.meta/example.rb, languages/ruby/exercises/concept/conditionals-ternary/moviegoer.rb, languages/ruby/exercises/concept/conditionals-ternary/moviegoer_test.rb
This is a draft and my first attempt at a concept exercise. Just wondering if anyone has any thoughts on my implementation. Is the introduction clear enough? Is this a good scenario/are the tasks appropriate?
I was considering including something about assignment using the ternary operator but maybe that's something that can go in `after.md`. I'm not really sure what to put in `hints.md`.
=> [Ruby] Implement new Concept Exercise: conditionals-ternary #1903

badges.md
Reopened https://github.com/exercism/v3/pull/1744
(cc @ynfle @kotp)
=> [Badges] Add Weekend Exerciser

languages/elixir/concepts/anonymous-functions/about.md, languages/elixir/concepts/basics/about.md, languages/elixir/concepts/basics/introduction.md, languages/elixir/concepts/bit-manipulation/about.md, languages/elixir/concepts/bit-manipulation/introduction.md, languages/elixir/concepts/bit-manipulation/links.json, languages/elixir/concepts/booleans/about.md, languages/elixir/concepts/booleans/introduction.md, languages/elixir/concepts/cond/about.md, languages/elixir/concepts/floating-point-numbers/about.md, languages/elixir/concepts/integers/about.md, languages/elixir/config.json, languages/elixir/exercises/concept/secrets/.docs/introduction.md
=> [Elixir] Concept blurbs and about.md's reviews

languages/c/reference/exercise-concepts/binary-search.md
[C] Extract concepts of v2 binary-search exercise
=> c: extract concepts of binary-search
